"""What must never be published, and what must never be claimed.

Guarantee 4 in ``docs/ARCHITECTURE.md`` says text that a redaction failed to
remove is never published: the build stops instead. This file is where that
guarantee is checked, so the tests are written to be read rather than merely to
pass. Each one names the property it defends in its docstring, and the two
kinds of failure are kept apart on purpose:

* **A false negative in hidden text can burn a source.** Those tests are
  labelled ``leak``. Several run twice, once against a real rendering of the
  page and once blind, because the pipeline runs in both configurations and
  the property has to hold in both of them.
* **A false positive in visible redactions makes the ledger lie.** Those tests
  are labelled ``decoy`` and each one names the specific thing that would
  otherwise have been counted as a redaction.

Everything is generated by ``tests/synth.py``. No fixtures, no third party's
documents, and no network.
"""

from __future__ import annotations

import dataclasses
import functools
import time
from dataclasses import dataclass, field

import numpy as np
import pytest
from PIL import Image, ImageDraw

import synth
from stackroom.imaging import (
    binarise,
    connected_components,
    is_uniform,
    otsu_threshold,
    to_gray,
    uniformity,
)
from stackroom.ingest.redaction import (
    RedactionFindings,
    _candidates,
    _CharIndex,
    _Crop,
    _is_dark,
    _page_parts,
    analyse_page,
    content_area,
    find_hidden_text,
    find_visible_redactions,
    redaction_ratio,
)
from stackroom.model import Box, Redaction, RedactionKind

BLACK = (0.0, 0.0, 0.0)
WHITE = (1.0, 1.0, 1.0)


# --------------------------------------------------------------------------
# stand-ins for ingest/pdf.py
#
# That module owns RawPage/RawChar/RawRect and may not exist yet. Everything
# under test reads a small structural contract - x0/top/x1/bottom in points,
# a colour, and `seq`, the position in the content stream - so these three
# dataclasses are a complete stand-in for it, and building a page by hand is
# the only way to test the awkward cases in isolation.
# --------------------------------------------------------------------------


@dataclass
class Char:
    text: str
    x0: float
    top: float
    x1: float
    bottom: float
    seq: int
    colour: tuple[float, float, float] = BLACK


@dataclass
class Rect:
    x0: float
    top: float
    x1: float
    bottom: float
    seq: int
    colour: tuple[float, float, float] = BLACK
    fill: bool = True
    opacity: float = 1.0


@dataclass
class RawPage:
    width: float = 612.0
    height: float = 792.0
    chars: list[Char] = field(default_factory=list)
    rects: list[Rect] = field(default_factory=list)


def text_run(text: str, x: float, top: float, *, seq: int, size: float = 10.5,
             colour: tuple[float, float, float] = BLACK) -> list[Char]:
    """A line of monospaced-ish characters starting at ``(x, top)``, in points."""
    advance = size * 0.55
    return [
        Char(
            text=ch,
            x0=x + i * advance,
            top=top,
            x1=x + (i + 1) * advance,
            bottom=top + size,
            seq=seq + i,
            colour=colour,
        )
        for i, ch in enumerate(text)
    ]


def flat_renderer(level: int = 0):
    """A crop renderer that says every box is a solid block of one colour."""
    return lambda box: Image.new("L", (120, 40), level)


def textured_renderer(box_level: int = 0, ink_level: int = 255):
    """A crop renderer that says every box has lettering standing out on it.

    This is what a highlight over live text looks like, and what a black box
    with white lettering painted on top looks like: the glyphs are in the
    pixels, so a reader can see them.
    """

    def render(box: Box) -> Image.Image:
        img = Image.new("L", (160, 40), box_level)
        draw = ImageDraw.Draw(img)
        for i in range(0, 160, 8):
            draw.rectangle([i + 2, 8, i + 5, 32], fill=ink_level)
        return img

    return render


# --------------------------------------------------------------------------
# stand-ins for ingest/raster.py, driven by a real PDF
# --------------------------------------------------------------------------


def _stream_objects(container):
    """Every drawable in content-stream order, descending into form XObjects.

    ``ingest/pdf.py`` is the module that owes the pipeline a real ``seq``; this
    is the same idea done crudely, and it is good enough to drive the tests
    because pdfminer with no layout analysis emits objects in paint order.
    """
    from pdfminer.layout import LTFigure

    for obj in container:
        if isinstance(obj, LTFigure):
            yield from _stream_objects(obj)
        else:
            yield obj


def raw_page(path, index: int = 0) -> RawPage:
    """Read a synthetic PDF into the stand-in objects above."""
    import pdfplumber
    from pdfminer.layout import LTChar, LTRect

    with pdfplumber.open(path) as pdf:
        page = pdf.pages[index]
        height = page.height
        chars: list[Char] = []
        rects: list[Rect] = []
        for seq, obj in enumerate(_stream_objects(page.layout)):
            if isinstance(obj, LTChar):
                chars.append(
                    Char(
                        text=obj.get_text(),
                        x0=obj.x0,
                        top=height - obj.y1,
                        x1=obj.x1,
                        bottom=height - obj.y0,
                        seq=seq,
                        colour=obj.graphicstate.ncolor,
                    )
                )
            elif isinstance(obj, LTRect):
                rects.append(
                    Rect(
                        x0=obj.x0,
                        top=height - obj.y1,
                        x1=obj.x1,
                        bottom=height - obj.y0,
                        seq=seq,
                        colour=getattr(obj, "non_stroking_color", None),
                        fill=bool(obj.fill),
                    )
                )
        return RawPage(width=page.width, height=page.height, chars=chars, rects=rects)


def pdf_renderer(path, index: int = 0, resolution: int = 200):
    """A ``crop_renderer`` over a real rendering of the page.

    Stands in for ``functools.partial(raster.render_page_crop, path, page)``.
    Renders once and crops, which is the contract the module documents: the
    image covers exactly the box it was asked for.
    """
    import pdfplumber

    with pdfplumber.open(path) as pdf:
        page = pdf.pages[index]
        try:
            image = page.to_image(resolution=resolution).original.convert("L")
        except Exception as exc:  # pragma: no cover - depends on the host
            pytest.skip(f"no page renderer available here: {exc!r}")
    width, height = image.size

    def render(box: Box) -> Image.Image:
        left, top = int(box.x * width), int(box.y * height)
        right, bottom = round(box.x2 * width), round(box.y2 * height)
        return image.crop((left, top, max(right, left + 1), max(bottom, top + 1)))

    return render


# The page body of a synthetic memo runs from about 104pt to 545pt down the
# page. Boxes for the hidden-text tests go below it, so that the only thing
# under them is the text the test put there.
CLEAR_Y = 200.0  # PDF user space, measured up from the bottom
CLEAR_Y2 = 170.0


def memo(tmp_path, specs, name="memo.pdf"):
    path = tmp_path / name
    synth.born_digital_pdf(path, pages=1, redactions={1: specs})
    return path


def both_ways(path):
    """The two configurations every hidden-text property must hold in."""
    return [("with a rendering", pdf_renderer(path)), ("blind", None)]


# ==========================================================================
# 1. Hidden text: the leaks
# ==========================================================================


def test_leak_failed_redaction_is_found_and_recovered(tmp_path):
    """A black box painted over live text is reported, with the text.

    This is the whole point of the module. The operator has to be shown what
    leaked, or they cannot judge how bad it is.
    """
    path = memo(tmp_path, [synth.RedactionSpec(90, CLEAR_Y, 200, 14, hidden_text="Gregory Aldana")])
    page = raw_page(path)

    for label, renderer in both_ways(path):
        found = find_hidden_text(page, crop_renderer=renderer)
        assert len(found) == 1, f"{label}: expected exactly one leak, got {found}"
        assert found[0].text == "Gregory Aldana", label
        assert found[0].redacted_repr() == "####### ######", label
        assert found[0].box.overlap_ratio(Box(0.14, 0.72, 0.34, 0.03)) > 0.9, label


def test_leak_same_colour_text_drawn_after_the_box(tmp_path):
    """Black text painted *on top of* a black box is still invisible.

    Draw order alone would clear this one - the text is painted last, so it is
    "on top" - but you cannot read black ink on a black box. This is a common
    shape for the bug: a tool stamps the box, then writes the text into it.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=10)],
        chars=text_run("Marta Oyelaran", x=92, top=602, seq=20),  # after the box
    )
    for renderer in (flat_renderer(), None):
        found = find_hidden_text(page, crop_renderer=renderer)
        assert [f.text for f in found] == ["Marta Oyelaran"]


def test_leak_recall_survives_a_missing_draw_order(tmp_path):
    """No ``seq`` from ingest/pdf.py must not mean no findings.

    Colour matching still fires, and ``analyse_page`` says out loud that the
    stronger test could not be run.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=None)],  # type: ignore[arg-type]
        chars=[
            Char(text=ch, x0=92 + i * 6, top=602, x1=98 + i * 6, bottom=612.5, seq=None)  # type: ignore[arg-type]
            for i, ch in enumerate("Anon Source")
        ],
    )
    assert [f.text for f in find_hidden_text(page)] == ["Anon Source"]
    assert any("draw order" in w for w in analyse_page(page).warnings)


def test_a_page_stamped_with_the_no_zorder_sentinel_has_no_draw_order(tmp_path):
    """``NO_ZORDER`` is *unknown*, and must never be read as a position.

    ``ingest/pdf.py`` stamps every shape on a page whose content stream it could
    not instrument with ``NO_ZORDER``, which is -1, and documents that callers
    must treat it as unknown and never as zero. This module used to test for a
    missing draw order by looking for ``seq is None`` - a value ``ingest/pdf.py``
    never emits - so on that whole degraded path the draw-order test silently
    answered "no" for every pair of shapes, and the warning written to catch
    exactly that never fired.

    The reproduction is the one from the review: a black box over ten glyphs,
    every ``seq`` -1, the characters a different ink from the box, so that
    colour matching cannot speak either. Before the fix this page came back
    ``hidden: []``, ``warnings: []`` - a clean bill of health for a page nobody
    had checked.
    """
    from stackroom.ingest.pdf import NO_ZORDER

    assert NO_ZORDER < 0, "the sentinel has to be outside the range of a real position"

    def page_with(seq_for_box: int, seq_for_char) -> RawPage:
        return RawPage(
            rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=seq_for_box)],
            chars=[
                Char(
                    text=ch,
                    x0=92 + i * 6,
                    top=602,
                    x1=98 + i * 6,
                    bottom=612.5,
                    seq=seq_for_char if isinstance(seq_for_char, int) else seq_for_char(i),
                    colour=(0.35, 0.35, 0.35),  # not the box's ink
                )
                for i, ch in enumerate("Anon Source")
            ],
        )

    # With real positions the page reports the hidden text: the box is painted
    # after the characters, which is the whole draw-order test.
    real = analyse_page(page_with(99, lambda i: 1 + i))
    assert [f.text for f in real.hidden] == ["Anon Source"]

    # With the sentinel we cannot say - and saying so is the point.
    sentinel = analyse_page(page_with(NO_ZORDER, NO_ZORDER))
    assert sentinel.hidden == []
    assert any("without a draw order" in w for w in sentinel.warnings), (
        "a page judged without a draw order has to say so"
    )


def test_a_sentinel_seq_is_never_compared_against_a_real_one():
    """Half a page of sentinels must not make the other half look painted-under.

    ``ingest/pdf.py`` decides per page, so today every shape on a page shares a
    fate. If that ever stops being true, ``-1 < 5`` must not be read as "this
    character was painted before that box": that is arithmetic on a value that
    means "we do not know".
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=5)],
        chars=[
            Char(text=ch, x0=92 + i * 6, top=602, x1=98 + i * 6, bottom=612.5,
                 seq=-1, colour=(0.35, 0.35, 0.35))
            for i, ch in enumerate("Anon Source")
        ],
    )
    result = analyse_page(page)
    assert result.hidden == []
    assert any("without a draw order" in w for w in result.warnings)


def test_a_page_that_says_its_draw_order_is_unusable_is_believed():
    """``RawPage.has_zorder`` is honoured, and it used to be called from nowhere.

    The per-shape sentinel and the per-page flag are two independent ways of
    being told the same thing, and this module reads both: a caller whose
    sentinel is some other value still gets the honest answer.
    """

    @dataclass
    class Unordered:
        width: float = 612.0
        height: float = 792.0
        chars: list = field(default_factory=list)
        rects: list = field(default_factory=list)
        has_zorder: bool = False

    page = Unordered(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=99)],
        chars=[
            Char(text=ch, x0=92 + i * 6, top=602, x1=98 + i * 6, bottom=612.5,
                 seq=1 + i, colour=(0.35, 0.35, 0.35))
            for i, ch in enumerate("Anon Source")
        ],
    )
    result = analyse_page(page)
    assert result.hidden == [], "the positions are there but the page says not to trust them"
    assert any("without a draw order" in w for w in result.warnings)


def test_leak_stacked_boxes_are_two_redactions_not_one_span(tmp_path):
    """Two stacked boxes stay two boxes, and the gap between them stays visible.

    A multi-line redaction drawn as one path has an outer bounding box that
    covers the visible text between the lines. Anything that reads that bbox
    instead of the individual sub-rectangles reports text nobody hid, and an
    operator who is shown two false leaks stops reading the third.
    """
    page = RawPage(
        rects=[
            Rect(x0=90, top=600, x1=290, bottom=616, seq=100),
            Rect(x0=90, top=640, x1=290, bottom=656, seq=101),
        ],
        chars=(
            text_run("Hidden line one", x=92, top=602, seq=1)
            + text_run("PLAINLY VISIBLE", x=92, top=622, seq=40)  # in the gap
            + text_run("Hidden line two", x=92, top=642, seq=70)
        ),
    )
    findings = find_hidden_text(page, crop_renderer=flat_renderer())
    assert [f.text for f in findings] == ["Hidden line one", "Hidden line two"]
    assert all("VISIBLE" not in f.text for f in findings)

    result = analyse_page(page)
    assert len(result.redactions) == 2
    assert {round(r.box.h, 6) for r in result.redactions} == {round(16 / 792, 6)}


def test_leak_reported_even_when_the_box_carries_a_label(tmp_path):
    """A box that is not flat all over can still be hiding text.

    Real productions stamp "(b)(6)" or a white "REDACTED" onto the box. The
    rendering is then not uniform, so the box-level check cannot clear it - and
    the per-character check still can, because a glyph that is under the box
    has nothing but box colour in its own footprint.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=100)],
        chars=text_run("Kept Underneath", x=92, top=602, seq=1),
    )

    def half_and_half(box: Box) -> Image.Image:
        # Flat black over the characters, a bright label in the right-hand
        # third, which is outside every character box in this page.
        img = Image.new("L", (200, 40), 0)
        ImageDraw.Draw(img).rectangle([170, 5, 195, 35], fill=255)
        return img

    assert [f.text for f in find_hidden_text(page, crop_renderer=half_and_half)] == [
        "Kept Underneath"
    ]


def test_leak_found_in_pdfplumbers_own_objects(tmp_path):
    """The page contract is read by name, not by type.

    ``ingest/pdf.py`` owns ``RawPage``; this module only ever asks for
    ``x0/top/x1/bottom``, a colour, and ``seq``, by any of the names those go
    by. Handing it pdfplumber's raw dictionaries - which have the geometry and
    ``non_stroking_color`` but no draw order at all - has to keep working, both
    because it is a plausible call site and because it is the configuration
    where only the colour test can speak.
    """
    import pdfplumber

    path = memo(
        tmp_path,
        [
            synth.RedactionSpec(90, CLEAR_Y, 200, 14, hidden_text="Gregory Aldana"),
            synth.RedactionSpec(
                90, CLEAR_Y2, 200, 14, hidden_text="Visible Overlay", draw_text_after=True
            ),
        ],
    )
    with pdfplumber.open(path) as pdf:
        page = pdf.pages[0]
        as_dicts = {
            "width": page.width,
            "height": page.height,
            "chars": page.chars,
            "rects": page.rects,
        }
        assert [f.text for f in find_hidden_text(as_dicts)] == ["Gregory Aldana"]
        assert any("without a draw order" in w for w in analyse_page(as_dicts).warnings)


def test_a_page_that_is_not_a_raw_page_is_refused():
    """Handing this a model.Page must fail loudly, not return "nothing found".

    A silent empty result from the wrong argument type is a safety check that
    looks like it ran.
    """
    from stackroom.model import Page

    with pytest.raises(TypeError, match=r"not a model\.Page"):
        find_hidden_text(Page(number=1))


# ==========================================================================
# 2. Hidden text: the things that only look like leaks
# ==========================================================================


def test_decoy_white_text_drawn_on_top_of_the_box_is_visible(tmp_path):
    """THE critical true negative: text on top of a box is not hidden text.

    ``synth.RedactionSpec(draw_text_after=True)`` writes white lettering over
    the black box - a caption, a label, a form field. A reader can see it. If
    this is reported as a leak the build stops on a page that is perfectly
    safe, and after the third such stop nobody believes the tool.

    Both configurations reject it, and for different reasons, which is the
    point: the draw order says the text is on top, and the pixels say the
    glyphs are right there on the box.
    """
    path = memo(
        tmp_path,
        [
            synth.RedactionSpec(
                90, CLEAR_Y, 200, 14, hidden_text="Visible Overlay", draw_text_after=True
            )
        ],
    )
    page = raw_page(path)
    for label, renderer in both_ways(path):
        found = find_hidden_text(page, crop_renderer=renderer)
        assert found == [], f"{label}: visible lettering reported as hidden: {found}"


def test_decoy_the_table_rule_is_never_a_redaction(tmp_path):
    """synth.py draws a 468 x 0.9pt rule on every page. It hides nothing.

    Thin filled rectangles are the most common shape in any document that has
    a table, a letterhead or an underline in it. One dimension under 4pt is
    enough to disqualify.
    """
    path = memo(tmp_path, [synth.RedactionSpec(90, CLEAR_Y, 200, 14, hidden_text="Real Leak")])
    page = raw_page(path)
    rule = [r for r in page.rects if r.bottom - r.top < 1.0]
    assert rule, "fixture no longer draws the table rule; this test is not testing anything"

    result = analyse_page(page, crop_renderer=pdf_renderer(path))
    assert len(result.redactions) == 1
    assert result.redactions[0].box.h > 0.01
    assert [f.text for f in result.hidden] == ["Real Leak"]


def test_decoy_running_header_band_is_ignored(tmp_path):
    """Rectangles wholly inside the top 43pt are page furniture.

    Inherited from x-ray. This is also a **documented blind spot**: a redaction
    that lives entirely in the letterhead - a name blacked out of a header - is
    not reported. The test asserts the blind spot rather than hiding it, so
    that anyone who narrows it can see exactly which test to change.
    """
    page = RawPage(
        rects=[Rect(x0=72, top=18, x1=300, bottom=34, seq=100)],  # bottom 34 < 43
        chars=text_run("Letterhead Name", x=74, top=20, seq=1),
    )
    assert find_hidden_text(page, crop_renderer=flat_renderer()) == []


def test_a_tall_box_starting_in_the_header_band_is_still_examined():
    """The band test is "wholly inside", not "starts inside".

    x-ray drops any rectangle whose top edge is above 43pt, which also drops a
    genuine full-column redaction that begins high on the page. Dropping a real
    redaction is the failure this module exists to prevent, so the rule is
    narrowed here and this test pins the difference.
    """
    page = RawPage(
        rects=[Rect(x0=72, top=30, x1=300, bottom=500, seq=100)],
        chars=text_run("Whole Column Withheld", x=74, top=200, seq=1),
    )
    assert [f.text for f in find_hidden_text(page, crop_renderer=flat_renderer())] == [
        "Whole Column Withheld"
    ]


def test_decoy_a_highlight_over_live_text_is_not_a_leak():
    """Pixels overrule the content stream when they disagree.

    A highlight is a filled rectangle painted over text, and pdfplumber cannot
    always see that it is transparent, so the draw-order rule alone calls every
    highlighted line a failed redaction. Rendering the box settles it: the
    words are in the pixels, so they are not hidden. The box is not dropped
    silently - it comes back as a warning for a human.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=100, colour=(1.0, 1.0, 0.0))],
        chars=text_run("Emphasised not hidden", x=92, top=602, seq=1),
    )
    assert find_hidden_text(page, crop_renderer=textured_renderer(box_level=230, ink_level=20)) == []

    result = analyse_page(
        page, crop_renderer=textured_renderer(box_level=230, ink_level=20)
    )
    assert result.hidden == []
    assert any("check this box by hand" in w for w in result.warnings)


def test_a_highlight_with_spaces_in_it_still_asks_for_a_human(tmp_path):
    """The hand-check warning must not be silenced by the phrase's word spacing.

    A real highlight, rendered: black prose with a see-through yellow rectangle
    over it, which pdfplumber reports as an opaque fill painted after the text.
    Every letter stands out of its own cell, so nothing is reported - and the
    warning that says so is the only thing that reaches the operator.

    Under a black rectangle the spaces are box colour; under a yellow one they
    are yellow, and either way they are the one part of the run whose cells are
    flat. Testing the raw covered list for emptiness therefore made this
    warning depend on whether the highlighted phrase happened to contain a
    space: the same document, one word shorter, warned.
    """
    from reportlab.lib.pagesizes import LETTER
    from reportlab.pdfgen import canvas

    for phrase in ("Emphasised not hidden", "Emphasised"):
        path = tmp_path / f"highlight-{len(phrase.split())}.pdf"
        c = canvas.Canvas(str(path), pagesize=LETTER)
        c.setFillColorRGB(0, 0, 0)
        c.setFont("Helvetica", 10.5)
        c.drawString(92, 600, phrase)
        c.setFillAlpha(0.35)
        c.setFillColorRGB(1.0, 1.0, 0.0)
        c.rect(90, 596, 200, 16, stroke=0, fill=1)
        c.setFillAlpha(1)
        c.showPage()
        c.save()

        result = analyse_page(raw_page(path), crop_renderer=pdf_renderer(path, resolution=150))
        assert result.hidden == [], phrase
        assert result.covered == [], f"{phrase}: highlighted text withheld from the page"
        assert any("check this box by hand" in w for w in result.warnings), (
            f"{phrase}: the operator was told nothing about a box the check declined "
            f"to clear: {result.warnings}"
        )


def test_decoy_a_date_only_page_is_suppressed(tmp_path):
    """When every box on the page hides a date, it is a form, not a leak.

    Docket sheets and logs draw cell rules over the dates in them. One date
    among several names is still a redaction, so the test is over the whole
    set - and the suppression is announced rather than silent.
    """
    path = memo(
        tmp_path,
        [
            synth.RedactionSpec(90, CLEAR_Y, 90, 14, hidden_text="03/14/2019"),
            synth.RedactionSpec(90, CLEAR_Y2, 90, 14, hidden_text="11/2/21"),
        ],
    )
    page = raw_page(path)
    renderer = pdf_renderer(path)
    assert find_hidden_text(page, crop_renderer=renderer) == []
    assert any("bare date" in w for w in analyse_page(page, crop_renderer=renderer).warnings)


def test_a_date_among_names_is_still_reported(tmp_path):
    """The date rule must not become a way to smuggle a name past the check."""
    path = memo(
        tmp_path,
        [
            synth.RedactionSpec(90, CLEAR_Y, 120, 14, hidden_text="03/14/2019"),
            synth.RedactionSpec(90, CLEAR_Y2, 120, 14, hidden_text="Gregory Aldana"),
        ],
    )
    page = raw_page(path)
    found = find_hidden_text(page, crop_renderer=pdf_renderer(path))
    assert sorted(f.text for f in found) == ["03/14/2019", "Gregory Aldana"]


@pytest.mark.parametrize(
    "junk",
    ["xxxxxxxxxx", "████", "....", "REDACTED", "Name Redacted", "-- --"],
)
def test_decoy_junk_strings_under_a_box_are_not_reported(junk):
    """Padding, box-drawing glyphs and the word "REDACTED" are not a leak.

    Every one of these is a real shape of false positive: a producer that fills
    the redaction with a run of one character, or stamps the word under its own
    box. Reporting them trains the operator to click through.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=390, bottom=616, seq=100)],
        chars=text_run(junk, x=92, top=602, seq=1),
    )
    assert find_hidden_text(page, crop_renderer=flat_renderer()) == []


def test_decoy_a_see_through_or_unfilled_rectangle_hides_nothing():
    """Opacity and fill are part of "opaque filled rectangle"."""
    covered = text_run("Under the shape", x=92, top=602, seq=1)
    for rect in (
        Rect(x0=90, top=600, x1=290, bottom=616, seq=100, opacity=0.35),
        Rect(x0=90, top=600, x1=290, bottom=616, seq=100, fill=False),
    ):
        page = RawPage(rects=[rect], chars=covered)
        assert find_hidden_text(page, crop_renderer=flat_renderer()) == []
        assert analyse_page(page).redactions == []


def test_one_tall_box_over_two_lines_recovers_them_in_reading_order():
    """A paragraph under a single box comes back readable, line by line.

    The operator has to be able to read what leaked. Characters sorted by
    position without grouping them into lines first produce a scramble, and a
    scrambled leak report is one an operator cannot act on.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=390, bottom=640, seq=100)],
        chars=(
            text_run("First line here", x=92, top=602, seq=1)
            + text_run("Second line here", x=92, top=622, seq=40)
        ),
    )
    found = find_hidden_text(page, crop_renderer=flat_renderer())
    assert [f.text for f in found] == ["First line here\nSecond line here"]


def test_a_line_the_box_only_just_covers_is_still_a_leak():
    """A box drawn a hair too high still hides the line under it.

    85% of each character is inside, which is over the bar, so this is a leak -
    and the character's top edge is *above* the box's, which is the case a
    naive lookup of "characters starting inside this rectangle" would miss
    entirely. Redaction boxes are placed by hand and by tools with rounding
    errors; they do not line up.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600.6, x1=290, bottom=616, seq=100)],
        chars=text_run("Only just under", x=92, top=599.0, seq=1),
    )
    assert [f.text for f in find_hidden_text(page, crop_renderer=flat_renderer())] == [
        "Only just under"
    ]


def test_a_character_only_clipped_by_the_box_is_not_covered():
    """80% of the character has to be inside, or descenders leak in.

    A line of visible text whose descenders touch the top of a box below it is
    not hidden, and counting it would put visible words in the leak report.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=100)],
        chars=text_run("Just above", x=92, top=592, seq=1),  # 2.5pt of 10.5 inside
    )
    assert find_hidden_text(page, crop_renderer=flat_renderer()) == []


def test_a_glyph_with_no_area_is_judged_by_its_centre():
    """Zero-width and zero-height glyphs must not fall through the check.

    Some producers emit characters whose bounding box has no area at all -
    spacing glyphs, glyphs under an odd text matrix. There is no fraction to
    take of zero, so 80%-inside cannot be asked; the centre point is asked
    instead. Dropping them silently would be a leak that never appears in any
    report.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=100)],
        chars=[
            Char(text=ch, x0=92 + i * 6, top=606, x1=92 + i * 6, bottom=606, seq=i)
            for i, ch in enumerate("Flat Glyphs")
        ],
    )
    found = find_hidden_text(page, crop_renderer=flat_renderer())
    assert [f.text.replace(" ", "") for f in found] == ["FlatGlyphs"]


def test_more_than_half_covered_is_still_not_covered():
    """The bar is 80% of the character, not "most of" it.

    A line whose lower half is under a box below it is still readable - the
    top halves of letters carry most of the shape - so 57% coverage is not a
    leak. This is x-ray's threshold and it is a real trade: a character that is
    79% covered is reported as visible, and there will be edge cases where that
    is generous. It is pinned here so that anyone who moves it has to say so.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=606, x1=290, bottom=616, seq=100)],
        chars=text_run("Half under", x=92, top=602, seq=1),  # 6pt of 10.5 inside
    )
    assert find_hidden_text(page, crop_renderer=flat_renderer()) == []


def test_text_in_a_different_colour_on_top_of_a_box_is_not_hidden():
    """Painted last, in a colour you can see, is not a failed redaction.

    Without a rendering the only thing separating "black on black" from "grey
    on black" is the colour comparison, so the tolerance on it has to be tight
    enough to be a real test rather than a formality.
    """
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=10, colour=BLACK)],
        chars=text_run("Legible caption", x=92, top=602, seq=20, colour=(0.5, 0.5, 0.5)),
    )
    assert find_hidden_text(page) == []


# --------------------------------------------------------------------------
# 2b. The page withheld in full
#
# A filled rectangle the size of the page with `(b)(5) PAGE WITHHELD IN FULL`
# reversed out of it in white is one of the most ordinary things in a FOIA
# corpus: it is what an agency produces for a page it is not releasing. It was
# also, until these tests, reported as a failed redaction - the loudest thing
# this module can say - because `box_is_flat` measures std and a percentile
# span over the whole rectangle, and a line of 10pt lettering is 0.2% of a
# page-sized box. Measured at 150 dpi it read std 10.5 and spread 0, inside
# both cuts, and every character the file reported inside the box was then
# called invisible without anybody looking at the characters.
#
# The two tests below are the two directions of that confusion and they use
# the same page: lettering that contrasts with the fill is a design and must
# never be reported, lettering in the fill's own ink is a leak and must always
# be. Everything after them re-checks the genuine cases at that same scale,
# because the page-sized box is exactly where the old shortcut was doing the
# deciding.
# --------------------------------------------------------------------------


def withheld_in_full(tmp_path, name, *, ink, text_first=False, box_h=600.0, size=10.0):
    """A page-sized black rectangle with a line of lettering across it.

    *ink* is the lettering's colour and *text_first* whether it goes down
    before the rectangle. ``(WHITE, text_first=False)`` is the stamp a real
    agency prints; ``(BLACK, ...)`` is the same page with the words invisible,
    which is a leak whichever order they were painted in.
    """
    from reportlab.lib.pagesizes import LETTER
    from reportlab.pdfgen import canvas

    path = tmp_path / name
    width, _height = LETTER
    c = canvas.Canvas(str(path), pagesize=LETTER)
    c.setFont("Helvetica-Bold", size)
    top = 740.0

    def lettering():
        c.setFillColorRGB(*ink)
        c.drawString(60, top - size * 2, "(b)(5) PAGE WITHHELD IN FULL")

    if text_first:
        lettering()
    c.setFillColorRGB(0, 0, 0)
    c.rect(50, top - box_h, width - 100, box_h, stroke=0, fill=1)
    if not text_first:
        lettering()
    c.showPage()
    c.save()
    return path


def test_decoy_a_page_withheld_in_full_is_not_a_failed_redaction(tmp_path):
    """THE false alarm: white lettering reversed out of a page-sized box.

    An operator who is shown "this document leaks" on a page that is obviously
    fine learns to disbelieve the alarm, and the alarm is the whole product.

    The assertion on ``box_is_flat`` is not decoration: it pins that this page
    still takes the path that used to fail, so that a future change which
    happens to make the box read as textured cannot quietly turn this test
    into one that proves nothing.
    """
    path = withheld_in_full(tmp_path, "withheld.pdf", ink=WHITE)
    page = raw_page(path)

    box = _candidates(_page_parts(page)[0])[0]
    renderer = pdf_renderer(path)
    assert _Crop(box.box, renderer(box.box)).box_is_flat(), (
        "this page no longer reads as flat over the whole box, so it is no "
        "longer the reproduction it was written to be"
    )

    for label, renderer in both_ways(path):
        found = find_hidden_text(page, crop_renderer=renderer)
        assert found == [], f"{label}: a page withheld in full reported as a leak: {found}"

    result = analyse_page(page, crop_renderer=pdf_renderer(path))
    assert result.hidden == []
    assert result.is_leaking is False
    # It is still a redaction: it is black and we cannot see through it.
    assert [r.kind for r in result.redactions] == [RedactionKind.VECTOR]


def test_a_box_over_the_gaps_between_visible_words_wipes_out_nothing(tmp_path):
    """The spaces between plainly visible words are not text the box removed.

    The same page as the test above, asked the ledger's question rather than
    the leak check's. Under that rectangle every letter of the heading stands
    out of its own cell and is not hidden - and the *spaces* between the words
    do not, because a space has no glyph in it and its cell really is solid box
    colour. ``_scan_hidden`` recorded "this box obliterated text" from that
    list before it tested whether any of it was whitespace, so the box went
    into ``covered``, which is the list ``pipeline._drop_hidden`` withholds
    every token of. The leak check stayed quiet, as it should, and the page
    silently lost its whole transcription and the exemption code printed on it.

    This is the ordinary layout for a page withheld in full, so the assertions
    below are written as the property rather than as the page: a box whose only
    covered characters are whitespace has wiped nothing out, and the visible
    glyphs beside them survive.
    """
    path = withheld_in_full(tmp_path, "withheld.pdf", ink=WHITE)
    page = raw_page(path)
    renderer = pdf_renderer(path)

    # The reproduction, stated so that a change which stops the spaces reading
    # as hidden turns this into a failure rather than a test of nothing.
    box = _candidates(_page_parts(page)[0])[0]
    crop = _Crop(box.box, renderer(box.box))
    covered = _CharIndex(_page_parts(page)[1]).covered(box)
    per_char = [(c.text, crop.hides(c.box)) for c in covered]
    # How many of the four space cells rasterise as solid box colour varies
    # with the poppler build - anti-aliasing at a cell edge can leave one
    # reading as visible - so the reproduction is the shape, not the count:
    # something hidden, all of it whitespace, and every real glyph visible.
    hidden_texts = [t for t, flat in per_char if flat]
    assert hidden_texts and all(t == " " for t in hidden_texts), per_char
    assert sum(1 for t, _ in per_char if t != " ") == 24, per_char
    assert all(flat is False for t, flat in per_char if t != " "), per_char

    result = analyse_page(page, crop_renderer=renderer)
    assert result.hidden == [], "the leak check must stay quiet on this page"
    assert result.covered == [], (
        "a box whose only hidden characters are the gaps between visible words "
        f"was recorded as having obliterated text: {result.covered}"
    )
    # It is still a redaction - it is black and a reader cannot see through it.
    assert [r.kind for r in result.redactions] == [RedactionKind.VECTOR]


def test_a_box_over_one_space_does_not_withhold_the_words_either_side():
    """The property with nothing else in the picture, and in both configurations.

    Three glyphs, ``A``, a space and ``B``, and a rectangle over the space
    alone. Whatever the renderer says about that cell, the box removed nothing:
    ``covered`` is what the pipeline withholds, and withholding here costs the
    reader both visible letters.
    """
    page = RawPage(
        rects=[Rect(x0=99, top=600, x1=106, bottom=616, seq=100)],
        chars=[
            Char(text="A", x0=92, top=602, x1=98.5, bottom=612.5, seq=1),
            Char(text=" ", x0=99.5, top=602, x1=105.5, bottom=612.5, seq=2),
            Char(text="B", x0=106.5, top=602, x1=113, bottom=612.5, seq=3),
        ],
    )
    for label, renderer in (("flat", flat_renderer()), ("blind", None)):
        result = analyse_page(page, crop_renderer=renderer)
        assert result.hidden == [], label
        assert result.covered == [], f"{label}: a box over one space withheld the words beside it"
        assert result.warnings == [], (
            f"{label}: a box that hid nothing produced a warning about hidden text: "
            f"{result.warnings}"
        )


def test_a_run_of_hidden_text_keeps_the_spaces_inside_it(tmp_path):
    """Whitespace stops counting as text, and does not stop being *in* the text.

    The two are easy to conflate and the recovered string is what an operator
    judges the leak by. ``Gregory Aldana`` is two words with a real space glyph
    between them; a fix that dropped the spaces from the run instead of from
    the count would report ``GregoryAldana``.
    """
    path = memo(tmp_path, [synth.RedactionSpec(90, CLEAR_Y, 200, 14, hidden_text="Gregory Aldana")])
    page = raw_page(path)
    for label, renderer in both_ways(path):
        result = analyse_page(page, crop_renderer=renderer)
        assert [f.text for f in result.hidden] == ["Gregory Aldana"], label
        assert len(result.covered) == 1, f"{label}: the box that hid it is still in the ledger"


def test_leak_lettering_in_the_boxs_own_ink_on_a_page_sized_box(tmp_path):
    """The other direction of the same confusion, on the same page.

    Black on black is a leak: the words are in the file, and nobody can see
    them. The only difference from the test above is the colour of the ink, so
    together they say that what decides this is the contrast between the glyph
    and the fill and not the size of the rectangle.
    """
    for text_first in (True, False):
        path = withheld_in_full(
            tmp_path, f"leak-{text_first}.pdf", ink=BLACK, text_first=text_first
        )
        page = raw_page(path)
        for label, renderer in both_ways(path):
            found = find_hidden_text(page, crop_renderer=renderer)
            assert [f.text for f in found] == ["(b)(5) PAGE WITHHELD IN FULL"], (
                f"{label}, text_first={text_first}: {found}"
            )


def test_a_flat_box_does_not_overrule_a_character_that_can_be_seen():
    """The mechanism, stated on its own so it cannot be lost by accident.

    ``box_is_flat`` is a statistic over the whole rectangle and one line of
    lettering is a rounding error in it. It may therefore answer only for
    characters that cannot be measured on their own, and only while no
    character contradicts it.

    The rendering here is a page-sized box, flat black except for the cells of
    seven characters, which are white: 0.15% of the pixels, which reads std
    10.0 - inside the cut, so the box-level test says *flat* - while every one
    of those seven cells is half white. The characters win, and the numbers are
    written down in the assertions so that a change to either threshold shows
    up here as a failure rather than as a silently different answer.
    """
    page = RawPage(
        rects=[Rect(x0=50, top=52, x1=562, bottom=740, seq=100)],
        chars=text_run("VISIBLE", x=60, top=60, seq=200, size=12, colour=WHITE),
    )
    crop_box = Box(50 / 612, 52 / 792, 512 / 612, 688 / 792)

    def lettering_on_a_black_page(box: Box) -> Image.Image:
        img = Image.new("L", (1000, 1344), 0)
        draw = ImageDraw.Draw(img)
        # One white stem in each glyph's cell. text_run puts the seven glyphs
        # at 60pt + 6.6pt each, 12pt tall; the crop covers 50..562 x 52..740pt,
        # so a cell is 12.9px wide and starts at 19.5 + 12.9i.
        for i in range(7):
            left = 19 + round(i * 12.9)
            draw.rectangle([left, 15, left + 5, 39], fill=255)
        return img

    crop = _Crop(crop_box, lettering_on_a_black_page(crop_box))
    assert crop.box_is_flat(), "the whole-box test has to be saying 'flat' here"
    assert crop.hides(Box(60 / 612, 60 / 792, 6.6 / 612, 12 / 792)) is False

    assert find_hidden_text(page, crop_renderer=lettering_on_a_black_page) == []


def test_genuine_leaks_survive_at_page_scale(tmp_path):
    """The three real shapes of a failed redaction, at the size that broke.

    A page-sized box is where ``box_is_flat`` used to decide everything, so
    demoting it has to be shown not to have cost any of them:

    * text painted before a covering rectangle - the ordinary failed redaction;
    * text painted after it in the rectangle's own ink - black on black;
    * a white rectangle dropped over live text - the white knockout, where the
      box is invisible and the words are the only thing that was there.
    """
    from reportlab.lib.pagesizes import LETTER
    from reportlab.pdfgen import canvas

    width, _height = LETTER

    def body(c, ink):
        c.setFillColorRGB(*ink)
        c.setFont("Helvetica", 10.5)
        y = 730.0
        for _ in range(38):
            c.drawString(60, y, "Marta Oyelaran met the contractor that morning.")
            y -= 15.2

    cases = {"before": (BLACK, True, BLACK), "after": (BLACK, False, BLACK),
             "knockout": (WHITE, True, BLACK)}
    for name, (fill, text_first, ink) in cases.items():
        path = tmp_path / f"page-{name}.pdf"
        c = canvas.Canvas(str(path), pagesize=LETTER)
        if text_first:
            body(c, ink)
        c.setFillColorRGB(*fill)
        c.rect(50, 140, width - 100, 600, stroke=0, fill=1)
        if not text_first:
            body(c, ink)
        c.showPage()
        c.save()

        page = raw_page(path)
        for label, renderer in both_ways(path):
            found = find_hidden_text(page, crop_renderer=renderer)
            assert found, f"{name} ({label}): a real leak went unreported"
            assert "Marta Oyelaran" in found[0].text, f"{name} ({label}): {found[0].text[:60]}"


def test_a_glyph_flush_with_the_edge_of_the_box_is_still_hidden(tmp_path):
    """The crop's outermost pixels are paper, and must not read as a glyph.

    ``render_page_crop`` rounds its crop outwards, so a character's cell at the
    very edge of a rectangle can reach a sliver of the page behind it. That did
    not matter while ``box_is_flat`` was answering for the whole box; now that
    each character answers for itself it decides real findings, and a genuinely
    buried glyph must not read as legible because of where the box happened to
    land between two pixels. Sweeping the box across a pixel is the reproducer:
    at two thirds of a pixel the cell went from std 0.0 to std 56.9.
    """
    from reportlab.lib.pagesizes import LETTER
    from reportlab.pdfgen import canvas

    for step in range(8):
        x = 90.0 + step / 8.0
        path = tmp_path / f"flush-{step}.pdf"
        c = canvas.Canvas(str(path), pagesize=LETTER)
        c.setFillColorRGB(0, 0, 0)
        c.setFont("Helvetica", 10.5)
        c.drawString(x, 603.0, "Marta Oyelaran")   # painted first: a real leak
        c.rect(x, 600.0, 90.0, 16.0, stroke=0, fill=1)
        c.showPage()
        c.save()

        found = find_hidden_text(raw_page(path), crop_renderer=pdf_renderer(path, resolution=150))
        assert found, f"box offset by {step}/8 of a pixel lost the leak under it"


# ==========================================================================
# 3. Hidden text: behaviour when the renderer is missing or broken
# ==========================================================================


def test_no_renderer_reports_on_the_content_stream_and_says_so(tmp_path):
    """Without pixels the module still answers, and flags the answer as unchecked.

    Policy, stated here because it is a judgement call and a reviewer should be
    able to argue with it: with no ``crop_renderer`` this falls back to the
    published x-ray rule - covered, and either painted before the box or in the
    box's own colour - and *reports*. Refusing to answer would mean a pipeline
    with no rasteriser silently loses the safety check, which is the worst of
    the options. What is lost is precision, not recall, so ``analyse_page``
    attaches a warning saying the finding was not confirmed against the page,
    and the CLI can show the operator that difference.
    """
    path = memo(tmp_path, [synth.RedactionSpec(90, CLEAR_Y, 200, 14, hidden_text="Gregory Aldana")])
    page = raw_page(path)

    result = analyse_page(page, crop_renderer=None)
    assert [f.text for f in result.hidden] == ["Gregory Aldana"]
    assert any("no page rendering was available" in w for w in result.warnings)
    assert result.is_leaking


def test_a_broken_renderer_degrades_to_the_content_stream():
    """A rasteriser that throws must not take the safety check down with it."""

    def broken(box: Box):
        raise RuntimeError("pdftoppm: I/O error")

    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=100)],
        chars=text_run("Still Reported", x=92, top=602, seq=1),
    )
    result = analyse_page(page, crop_renderer=broken)
    assert [f.text for f in result.hidden] == ["Still Reported"]
    assert any("crop renderer failed" in w for w in result.warnings)


def test_an_unusably_small_crop_is_treated_as_no_crop():
    """A 2x2 crop cannot confirm or deny anything; do not let it deny."""
    page = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=100)],
        chars=text_run("Tiny Crop", x=92, top=602, seq=1),
    )
    tiny = lambda box: Image.new("L", (2, 2), 255)  # noqa: E731
    result = analyse_page(page, crop_renderer=tiny)
    assert [f.text for f in result.hidden] == ["Tiny Crop"]
    assert any("too small to judge" in w for w in result.warnings)


# ==========================================================================
# 4. The ledger: which filled rectangles count as a redaction
#
# "N pages withheld, X% of content" is the most consequential number this tool
# prints, and a born-digital PDF is full of filled rectangles that withhold
# nothing at all. These tests are the ones that keep that number honest.
# ==========================================================================


def covered_text(fill, *, text_first=True, seq_rect=100):
    """A rectangle of *fill* colour with a line of text at the same place.

    ``text_first`` decides which of the two the content stream paints first,
    which is the whole difference between a redaction and a table cell.
    """
    return RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=seq_rect, colour=fill)],
        chars=text_run("Underneath", x=92, top=602, seq=1 if text_first else seq_rect + 1),
    )


def bare_rect(fill):
    """A rectangle of *fill* colour with nothing under it at all."""
    return RawPage(rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=100, colour=fill)])


def test_ledger_a_white_rectangle_over_nothing_is_furniture():
    """A knockout box clearing space for a stamp is not a redaction.

    Real PDFs are full of these - cell fills, header knockouts, whiteout over a
    scanning artefact, form backgrounds. One per page in the ledger and every
    percentage in the archive is wrong.
    """
    result = analyse_page(bare_rect(WHITE), crop_renderer=flat_renderer(255))
    assert result.redactions == []
    assert result.hidden == []


def test_ledger_a_white_rectangle_over_live_text_is_a_redaction_and_a_leak():
    """White-on-white: the box withheld something, and badly.

    A white rectangle dropped over text that is already on the page obliterates
    it on screen and leaves every word of it in the file. It belongs in the
    ledger *and* it stops the build.
    """
    page = covered_text(WHITE, text_first=True)
    for renderer in (flat_renderer(255), None):
        assert [f.text for f in find_hidden_text(page, crop_renderer=renderer)] == [
            "Underneath"
        ]
    result = analyse_page(page, crop_renderer=flat_renderer(255))
    assert [r.kind for r in result.redactions] == [RedactionKind.VECTOR]
    assert [f.text for f in result.hidden] == ["Underneath"]


def test_ledger_a_black_rectangle_over_nothing_is_a_redaction():
    """A box over a photograph or a signature has no characters to find.

    Nothing in the content stream says what was there, so darkness is the only
    evidence available - and it is enough: a reader cannot see through it.
    """
    result = analyse_page(bare_rect(BLACK), crop_renderer=flat_renderer(0))
    assert [r.kind for r in result.redactions] == [RedactionKind.VECTOR]
    assert result.hidden == []


def test_ledger_a_black_rectangle_over_live_text_is_a_redaction_and_a_leak():
    """The ordinary failed redaction, counted once and reported once."""
    page = covered_text(BLACK, text_first=True)
    result = analyse_page(page, crop_renderer=flat_renderer(0))
    assert [r.kind for r in result.redactions] == [RedactionKind.VECTOR]
    assert [f.text for f in result.hidden] == ["Underneath"]


def test_ledger_a_cell_fill_under_its_own_text_is_furniture():
    """Painted *before* the text sitting in it, so it covers without hiding.

    This is why "covers characters" is not the test on its own. A shaded table
    cell contains its own text geometrically; it withheld nothing, and a table
    of forty such cells would otherwise report forty redactions.
    """
    for fill in (WHITE, (0.9, 0.9, 0.9), (0.75, 0.8, 1.0)):
        page = covered_text(fill, text_first=False)
        result = analyse_page(page, crop_renderer=textured_renderer(230, 20))
        assert result.redactions == [], fill
        assert result.hidden == [], fill


@pytest.mark.parametrize(
    ("grey", "counted"),
    [(0.0, True), (0.15, True), (0.25, True), (0.35, False), (0.6, False), (1.0, False)],
)
def test_ledger_a_grey_box_over_nothing_is_counted_only_if_it_is_dark(grey, counted):
    """Where the line sits for a mid-grey box, and why it is drawn there.

    Some agencies redact in grey rather than black, so the cut is not
    "near-black": it is the same luma the raster pass uses for a rendered block
    (mean 70 of 255, so 0.275 here). Drawing it anywhere else would let
    ``analyse_page`` disagree with itself, counting a grey vector fill and then
    not counting the grey block that same fill renders into.

    A grey box that covers text is counted whatever its shade - see the next
    test - so what this threshold decides is only the fate of a grey box with
    nothing under it, which is a shaded panel far more often than a redaction.
    """
    fill = (grey, grey, grey)
    found = analyse_page(bare_rect(fill), crop_renderer=flat_renderer(round(grey * 255)))
    assert bool(found.redactions) is counted


@pytest.mark.parametrize("grey", [0.0, 0.3, 0.5, 0.75])
def test_ledger_a_grey_box_over_live_text_is_always_counted(grey):
    """Shade decides nothing once the box is known to have wiped text out."""
    page = covered_text((grey, grey, grey), text_first=True)
    result = analyse_page(page, crop_renderer=flat_renderer(round(grey * 255)))
    assert len(result.redactions) == 1


def test_the_ledger_filter_does_not_narrow_the_leak_check():
    """THE separation: tightening the ledger must never blind the safety check.

    The ledger ignores a light rectangle that covers nothing. The leak check
    considers rectangles of *every* colour, because a white box painted over
    live text is a whole class of failed redaction and is invisible to a rule
    that only looks at dark fills. Anyone who later tightens the ledger further
    has to come through this test to do it.
    """
    for fill in (WHITE, (1.0, 1.0, 0.0), (0.97, 0.97, 0.9), (0.5, 0.5, 0.5), BLACK):
        # Covering nothing: the ledger's business, and it varies by colour.
        assert (analyse_page(bare_rect(fill)).redactions != []) is _is_dark(fill)
        # Covering live text: the leak check's business, and it does not.
        page = covered_text(fill, text_first=True)
        assert [f.text for f in find_hidden_text(page, crop_renderer=flat_renderer(200))] == [
            "Underneath"
        ], fill
        assert [f.text for f in find_hidden_text(page)] == ["Underneath"], fill


@pytest.mark.parametrize(
    ("fill", "counted"),
    [
        ((0.0, 0.0, 1.0), True),  # navy: renders at grey 29, unreadable
        ((0.4, 0.0, 0.0), True),  # maroon: grey 30
        ((0.0, 1.0, 0.0), False),  # saturated green: grey 150, text reads fine
        ((1.0, 1.0, 0.0), False),  # yellow, i.e. a highlight
    ],
)
def test_ledger_darkness_is_luma_not_the_average_channel(fill, counted):
    """A coloured box is judged by how dark it *looks*.

    Green at full strength and navy at full strength have the same channel
    average and nothing else in common: one renders at grey 150 and you can
    read straight through it, the other at grey 29 and you cannot. The eye
    weights green six times more than blue, so the test has to as well - and it
    has to agree with ``imaging.to_gray``, or the vector and raster passes
    would classify the same box differently.
    """
    found = analyse_page(bare_rect(fill))
    assert bool(found.redactions) is counted


def test_ledger_a_fill_we_cannot_read_is_not_assumed_to_be_a_redaction():
    """An uninterpretable colour keeps its box out of the ledger, not out of the check.

    Pattern fills, separation inks and colour spaces we decline to guess at
    arrive as ``None``. For the ledger that means "no evidence of darkness", so
    the box is counted only if it can be shown to have covered something -
    the conservative answer for a number the whole archive is judged on. For
    the leak check it means nothing at all: the box is examined exactly as any
    other.
    """
    assert analyse_page(bare_rect(None)).redactions == []

    page = covered_text(None, text_first=True)
    result = analyse_page(page, crop_renderer=flat_renderer(0))
    assert [f.text for f in result.hidden] == ["Underneath"]
    assert len(result.redactions) == 1  # it covered text, so it is in the ledger


def test_a_box_hanging_off_the_page_is_still_mapped_correctly():
    """The crop contract, at the one place the two sides of it disagree.

    ``ingest/pdf.py`` deliberately does not clamp rectangles to the media box -
    full-bleed content is real, and moving a redaction box away from what it
    covers would be worse. Every renderer in the project deliberately does
    clamp, because there are no pixels outside the page. Ask for a box that
    hangs off the edge and you get back an image of *less* than you asked for,
    and every coordinate mapped into it is then wrong by the overhang - which
    silently clears real leaks, because the characters land on the wrong pixels.

    So the box is clipped to the page before it is asked for. The renderer here
    is a copy of the pipeline's, floor/ceil and clamped, and the page is built
    so that the wrong mapping lands the characters on lettering-like texture
    and the right one lands them on solid black.
    """
    page_px = Image.new("L", (1000, 500), 255)
    draw = ImageDraw.Draw(page_px)
    draw.rectangle([0, 200, 299, 249], fill=0)  # the on-page part of the box
    for stripe in range(100, 280, 8):  # lettering-like texture inside it
        draw.rectangle([stripe, 200, stripe + 3, 249], fill=255)

    def pipeline_cropper(box: Box) -> Image.Image:
        # Identical to pipeline._in_memory_cropper: outwards, then clamped.
        import math

        x0 = max(0, min(1000, math.floor(box.x * 1000)))
        y0 = max(0, min(500, math.floor(box.y * 500)))
        x1 = max(0, min(1000, math.ceil(box.x2 * 1000)))
        y1 = max(0, min(500, math.ceil(box.y2 * 500)))
        if x1 <= x0 or y1 <= y0:
            raise ValueError("empty crop")
        return page_px.crop((x0, y0, x1, y1))

    # The rectangle starts 20% of the page width off the left edge. The
    # characters are painted after it and in another colour, so the content
    # stream cannot vouch for them: only the pixels can.
    page = RawPage(
        rects=[Rect(x0=-122.4, top=316.8, x1=183.6, bottom=396.0, seq=10, colour=BLACK)],
        chars=text_run("ABC", x=12.24, top=332.64, seq=99, size=20, colour=WHITE),
    )
    found = find_hidden_text(page, crop_renderer=pipeline_cropper)
    assert [f.text for f in found] == ["ABC"]


def test_known_limitation_a_dark_bar_with_reversed_lettering_is_counted():
    """Stated, not hidden: a dark section header goes in the ledger.

    A dark bar with white lettering painted on top is a header in a modern
    report and a labelled redaction box in a FOIA release, and from the content
    stream the two are the same object: a dark fill with visible text on it.
    We count it, because the alternative - excluding any dark box that has text
    painted on top of it - drops the labelled redaction box, and under-reporting
    a redaction is the worse of the two errors.

    The cost is inflation on report-styled documents. If that turns out to
    matter more than the labelled box, the change is one clause and this test
    is where to make it.
    """
    header_bar = covered_text(BLACK, text_first=False)  # bar first, caption on top
    result = analyse_page(header_bar, crop_renderer=textured_renderer(0, 255))
    assert len(result.redactions) == 1
    assert result.hidden == []  # correctly not a leak: the lettering is visible


# ==========================================================================
# 5. Visible redactions in a rendered page
# ==========================================================================

# Text lines on a synthetic typed page occupy rows 154+40k to 175+40k, so a box
# from 146+40k to 183+40k covers one line whole and leaves 11px of paper on
# either side. Redactions that touch the glyphs of the next line up merge into
# one component with them - see the limitation test at the end of this section.
SCAN_BOXES = [(130, 266, 1210, 303), (130, 586, 1210, 623), (130, 1026, 1210, 1063)]


def scanned_page_with_decoys() -> Image.Image:
    """Three true redactions, a header rule, a scan border and a photograph."""
    image = synth.typed_page(redactions=SCAN_BOXES, photo_block=True, scan_border=True)
    ImageDraw.Draw(image).rectangle([100, 60, 1175, 62], fill=6)  # a header rule
    return image


def test_visible_redactions_three_of_three_and_no_decoys():
    """3/3 caught; the border, the photograph and the rule all rejected.

    The decoys are not incidental. Every scanned production has a black scan
    border, most have a photograph or a stamp somewhere, and all of them have
    rules. If any of these counts as a redaction then "37% withheld" is a
    number the archive made up.
    """
    found = find_visible_redactions(scanned_page_with_decoys())
    assert len(found) == 3, [f.box for f in found]
    assert all(r.kind is RedactionKind.RASTER for r in found)

    for (x0, y0, x1, y1), box in zip(SCAN_BOXES, sorted(found, key=lambda r: r.box.y), strict=True):
        expected = Box(x0 / 1275, y0 / 1650, (x1 - x0) / 1275, (y1 - y0) / 1650)
        assert box.box.overlap_ratio(expected) > 0.95
        assert expected.overlap_ratio(box.box) > 0.95


def test_decoy_scan_border_is_rejected():
    """The border of a skewed scan is black, page-sized and rectangular.

    It survives the size and page-fraction tests - a hollow frame is only a few
    percent of the page - so it has to be rejected on shape. On a portrait page
    two tests fire: the frame is taller than it is wide, and it fills 2% of its
    own bounding box. The next test isolates the second one.
    """
    image = synth.typed_page(scan_border=True)
    gray = to_gray(image)
    _, components = connected_components(binarise(gray, 60))
    border = max(components, key=lambda c: c.w * c.h)
    assert border.w > 1200 and border.h > 1600, "did not find the border component"
    assert border.solidity < 0.1  # the measurement MIN_SOLIDITY is set against
    assert border.area < 0.4 * gray.size, "the page-fraction test is not what saves us"
    assert find_visible_redactions(image) == []


def test_decoy_dark_scan_with_a_platen_edge_is_rejected_by_solidity():
    """Solidity on its own, with every other test satisfied.

    A landscape page scanned dark - uniformly just lighter than the near-black
    cut - with the black edge of the platen around it. The frame component is
    the right size, the right aspect, a small fraction of the page, and its
    interior is *flat and dark*, so the variance and brightness tests all pass
    it. Only the ratio of set pixels to bounding box says it is a frame and not
    a block. Without that test this page reports one page-sized redaction.
    """
    image = Image.new("L", (1650, 1275), 61)
    ImageDraw.Draw(image).rectangle([0, 0, 1649, 1274], outline=3, width=8)
    gray = to_gray(image)
    _, components = connected_components(binarise(gray, 60))
    frame = max(components, key=lambda c: c.w * c.h)
    std, spread, mean = uniformity(frame.crop(gray, inset=2))
    assert std < 12.0 and spread < 25.0 and mean < 70.0  # flatness would pass it
    assert 0.8 <= frame.aspect <= 60 and frame.area < 0.4 * gray.size  # so would shape
    assert frame.solidity < 0.05  # this is the only test that rejects it

    assert find_visible_redactions(image) == []


def test_decoy_dark_textured_block_is_rejected_by_interior_variance():
    """A solid dark photograph passes every geometric test. Its texture does not.

    This is the decoy the flatness thresholds exist for: a block that is dark
    enough to threshold as one solid component, big enough, and the right
    shape, but with a photograph's grain inside it. Measured here at std ~14
    and spread ~48 against a true box's 0.0.
    """
    rng = np.random.default_rng(4)
    patch = np.clip(rng.normal(30, 14, size=(260, 360)), 0, 58).astype(np.uint8)
    image = synth.blank_page()
    image.paste(Image.fromarray(patch), (700, 900))

    gray = to_gray(image)
    _, components = connected_components(binarise(gray, 60))
    block = max(components, key=lambda c: c.area)
    assert block.solidity > 0.99, "the decoy must be solid, or it proves nothing"
    std, spread, mean = uniformity(block.crop(gray, inset=2))
    assert std > 12 and spread > 25 and mean < 70

    assert find_visible_redactions(image) == []


def test_decoy_a_page_rule_is_too_thin_and_a_dark_page_too_large():
    """The two ends of the size filter: a 3px rule and an inverted scan."""
    ruled = synth.blank_page()
    ImageDraw.Draw(ruled).rectangle([100, 60, 1175, 62], fill=6)
    assert find_visible_redactions(ruled) == []

    inverted = synth.typed_page(invert=True)
    assert find_visible_redactions(inverted) == []


def test_decoy_a_dark_edge_band_is_rejected_by_aspect_alone():
    """A solid black strip down the side of a misfed scan.

    Solid, flat, black, and only 2% of the page, so nothing else in the chain
    touches it: it is rejected because a redaction is drawn over lines of text
    and is therefore not eighty times taller than it is wide.
    """
    image = synth.typed_page()
    ImageDraw.Draw(image).rectangle([0, 0, 30, 1649], fill=5)
    gray = to_gray(image)
    _, components = connected_components(binarise(gray, 60))
    band = max(components, key=lambda c: c.area)
    assert band.solidity > 0.99 and is_uniform(band.crop(gray, inset=2))  # everything else passes
    assert band.aspect < 0.8  # this is the only test that rejects it

    assert find_visible_redactions(image) == []


def test_decoy_a_page_scanned_black_is_rejected_by_size_alone():
    """A page photographed against a dark surface is not a page-sized redaction.

    Solid, flat, black, right aspect: the only thing wrong with it is that it
    is the whole page, and a page withheld in full arrives as a blank sheet
    with a control number on it, not as a black rectangle.
    """
    image = Image.new("L", (1650, 1275), 8)
    gray = to_gray(image)
    _, components = connected_components(binarise(gray, 60))
    whole = components[0]
    assert whole.solidity > 0.99 and is_uniform(whole.crop(gray, inset=2))
    assert 0.8 <= whole.aspect <= 60
    assert whole.area > 0.4 * gray.size  # this is the only test that rejects it

    assert find_visible_redactions(image) == []


def test_visible_redaction_thresholds_scale_with_resolution():
    """A box measured at 150 dpi is the same box at 300 dpi.

    The size thresholds are in pixels, so a caller that renders at another
    resolution and forgets to say so gets the wrong answer. Passing ``dpi``
    keeps the physical size constant.
    """
    small = synth.blank_page(640, 830)  # ~75 dpi letter
    ImageDraw.Draw(small).rectangle([100, 300, 500, 317], fill=4)  # 401 x 18 px
    assert len(find_visible_redactions(small, dpi=75)) == 1
    # 18px is 8.6pt at 75 dpi but only 4.3pt at 300, below the 4.8pt floor.
    assert find_visible_redactions(small, dpi=300) == []


@pytest.mark.parametrize("level", [65, 90, 150])
def test_decoy_a_grey_panel_is_not_a_redaction(level):
    """Shaded table cells and sidebars are darker than the paper. Not black.

    "What counts as ink on this page" is the wrong question to ask here, and an
    adaptive threshold answers that question: Otsu on this page cuts at 151 and
    calls the panel a solid block, flat inside and the right shape - a
    page-sized false redaction in the ledger. A redaction is not merely darker
    than the paper, so the cut for one is fixed.
    """
    image = synth.typed_page()
    # In the bottom margin, where nothing touches it: a panel joined to a line
    # of text would be rejected for the wrong reason and prove nothing.
    ImageDraw.Draw(image).rectangle([200, 1520, 900, 1580], fill=level)
    assert otsu_threshold(to_gray(image)) > level  # an adaptive cut would take it
    assert find_visible_redactions(image) == []


@pytest.mark.parametrize(("degrees", "expected"), [(0.0, 3), (0.1, 3), (0.2, 0), (1.0, 0)])
def test_known_limitation_the_raster_pass_needs_a_deskewed_page(degrees, expected):
    """Stated, not hidden: 0.2 degrees of skew and every box is lost.

    Solidity is measured against an upright bounding box, so rotating a
    1081 x 38px block by a fifth of a degree puts 9.5% of that box outside the
    ink and drops it under the 0.92 cut. Measured: 1.00 upright, 0.95 at 0.1,
    0.905 at 0.2, 0.67 at 1.0 degree. Ordinary scans are skewed by more than
    that, so this pass is only meaningful on a page that has been deskewed
    first, or on a rendering of a born-digital PDF.

    It costs the ledger, never the leak check: hidden text is found in the
    content stream, which has no idea the page was scanned crooked.
    """
    image = synth.typed_page(redactions=SCAN_BOXES, rotate=degrees)
    assert len(find_visible_redactions(image)) == expected


def test_known_limitation_a_box_touching_the_next_line_is_missed():
    """Stated, not hidden: glyphs that touch a box merge into it.

    Eight-connected labelling cannot tell a redaction from a redaction with a
    descender stuck to it, and the merged component's solidity falls below the
    cut. In a dense document with tight leading this loses real boxes from the
    ledger. It costs the ratio, never the leak check - hidden text is found in
    the content stream, which knows nothing about pixels.
    """
    touching = synth.typed_page(redactions=[(120, 296, 1160, 336)])
    assert find_visible_redactions(touching) == []


# ==========================================================================
# 6. Against the real ingest modules
# ==========================================================================


def test_it_fits_the_real_raw_page_and_the_real_renderer(tmp_path):
    """The contract this module states, checked against the modules that meet it.

    Everything above drives ``redaction.py`` through stand-ins, on purpose:
    those tests have to keep working while ``ingest/pdf.py`` is still being
    written. This one closes the loop. ``RawPage`` carries page-relative boxes
    and spells its colours ``fill_color``/``color``; ``render_page_crop`` takes
    ``(pdf, page, box)`` and rounds its crop outwards. If either of those
    drifts, the leak check quietly stops finding leaks, so it should be a
    failing test and not a surprise in production.
    """
    pdf = pytest.importorskip("stackroom.ingest.pdf")
    raster = pytest.importorskip("stackroom.ingest.raster")

    path = memo(
        tmp_path,
        [
            synth.RedactionSpec(90, CLEAR_Y, 200, 14, hidden_text="Gregory Aldana"),
            synth.RedactionSpec(
                90, CLEAR_Y2, 200, 14, hidden_text="Visible Overlay", draw_text_after=True
            ),
        ],
    )
    try:
        raster.page_geometry(path)
    except Exception as exc:  # pragma: no cover - no poppler on this host
        pytest.skip(f"pdftoppm/pdfinfo unavailable: {exc!r}")

    with pdf.open_pdf(path) as handle:
        page = pdf.read_page(handle, 0)

    render = functools.partial(raster.render_page_crop, path, 1)
    result = analyse_page(page, crop_renderer=render)
    assert [f.text for f in result.hidden] == ["Gregory Aldana"]
    assert result.warnings == []  # every finding confirmed against the pixels
    assert len(result.redactions) == 2
    assert find_hidden_text(page) == result.hidden  # and the same answer blind


def test_the_field_names_ingest_pdf_uses_are_the_ones_this_module_reads():
    """A rename in ``ingest/pdf.py`` must fail here, not degrade the check there.

    This module reads its inputs through alias tables so that a test can drive
    it with a three-line stand-in. The cost of that flexibility is that a
    renamed field on the real ``RawRect`` stops being a crash and becomes a
    shrug: ``_field`` falls through to the default, the same-colour half of the
    hidden-text test stops firing, and nothing says anything. This is the alarm.
    """
    from stackroom.ingest import pdf as pdf_mod
    from stackroom.ingest import redaction as module

    rect_names = {f.name for f in dataclasses.fields(pdf_mod.RawRect)}
    char_names = {f.name for f in dataclasses.fields(pdf_mod.RawChar)}
    page_names = {f.name for f in dataclasses.fields(pdf_mod.RawPage)} | {"has_zorder"}

    for owner, names, table, what in (
        ("RawRect", rect_names, module._COLOUR, "a fill colour"),
        ("RawChar", char_names, module._COLOUR, "a colour"),
        ("RawRect", rect_names, module._SEQ, "a draw order"),
        ("RawChar", char_names, module._SEQ, "a draw order"),
        ("RawPage", page_names, module._WIDTH, "a width"),
        ("RawPage", page_names, module._HEIGHT, "a height"),
        ("RawPage", page_names, module._ORDERED, "whether its draw order is usable"),
    ):
        assert names & set(table), (
            f"ingest/pdf.py's {owner} no longer carries {what} under any of {table!r}; "
            "redaction.py reads it through that table and would silently stop checking"
        )


def test_a_shape_with_no_colour_field_at_all_is_reported():
    """"Unknown colour" and "no colour field" must not look alike.

    A rect whose ``fill_color`` is None is an ordinary PDF telling us it used a
    colour space we decline to guess at, and the same-colour test simply does
    not fire. A rect with no colour field *at all* is this module reading a
    shape it does not understand - a renamed field, a new producer object - and
    half the hidden-text test is not running. One of those is a page note.
    """

    @dataclass
    class Colourless:
        x0: float
        top: float
        x1: float
        bottom: float
        seq: int
        fill: bool = True

    page = RawPage(
        rects=[Colourless(x0=90, top=600, x1=290, bottom=616, seq=99)],
        chars=[
            Char(text=ch, x0=92 + i * 6, top=602, x1=98 + i * 6, bottom=612.5, seq=1 + i)
            for i, ch in enumerate("Anon Source")
        ],
    )
    notes = analyse_page(page).warnings
    assert any("no fill-colour field" in w for w in notes), notes

    # An honest None is not a broken contract and says nothing.
    known = RawPage(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=99, colour=None)],
        chars=[
            Char(text=ch, x0=92 + i * 6, top=602, x1=98 + i * 6, bottom=612.5, seq=1 + i)
            for i, ch in enumerate("Anon Source")
        ],
    )
    assert not any("no fill-colour field" in w for w in analyse_page(known).warnings)


def test_a_page_with_no_size_field_is_reported_rather_than_assumed_to_be_letter():
    """Every box is placed against the page size, so a missing one is not a detail.

    ``_WIDTH``/``_HEIGHT`` default to US Letter when a page carries neither
    name, which keeps a three-line stand-in working and would keep working
    silently after a rename in ``ingest/pdf.py`` - with every box on every page
    placed against the wrong sheet. That is a black box drawn somewhere it is
    not, which is the failure this module exists to prevent.
    """

    @dataclass
    class Sizeless:
        chars: list = field(default_factory=list)
        rects: list = field(default_factory=list)

    page = Sizeless(
        rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=99)],
        chars=[
            Char(text=ch, x0=92 + i * 6, top=602, x1=98 + i * 6, bottom=612.5, seq=1 + i)
            for i, ch in enumerate("Anon Source")
        ],
    )
    notes = analyse_page(page).warnings
    assert any("no field naming a width" in w for w in notes), notes
    assert not any("no field naming" in w for w in analyse_page(RawPage(
        rects=page.rects, chars=page.chars
    )).warnings)


# ==========================================================================
# 7. How much was withheld
# ==========================================================================


def test_a_fully_blacked_page_reads_1_0_not_0_63():
    """The denominator is the inked region, not the sheet of paper.

    A letter page blacked from margin to margin is 63% of the sheet, because an
    inch of margin all round is 37% of it. An archive that reports 63% for a
    page a reader cannot read a word of is not being cautious, it is wrong.
    """
    text_area = Box(72 / 612, 72 / 792, 468 / 612, 648 / 792)
    assert text_area.area == pytest.approx(0.626, abs=0.01)  # the wrong answer

    ratio = redaction_ratio([Redaction(box=text_area, kind=RedactionKind.VECTOR)], [], (612, 792))
    assert ratio == pytest.approx(1.0, abs=0.001)


def test_ratio_counts_area_not_bounding_boxes():
    """Two boxes on one line are not counted twice, and blank leading is not content.

    Bounding boxes over-count on both sides of the fraction; the union of areas
    is the only version that survives double-spaced text and overlapping boxes.
    """
    words = [Box(0.1, 0.1 + 0.05 * i, 0.6, 0.02) for i in range(10)]  # 10 lines
    two_on_one_line = [
        Redaction(box=Box(0.1, 0.1, 0.3, 0.02), kind=RedactionKind.VECTOR),
        Redaction(box=Box(0.3, 0.1, 0.3, 0.02), kind=RedactionKind.VECTOR),  # overlapping
    ]
    ratio = redaction_ratio(two_on_one_line, words, (612, 792))
    assert ratio == pytest.approx(0.1, abs=0.02)  # one line of ten, not two


def test_ratio_of_a_page_with_no_ink_is_zero():
    """A blank page is not a fully redacted page."""
    assert redaction_ratio([], [], (612, 792)) == 0.0


def test_content_area_is_the_ratio_written_as_two_numbers():
    """The share and the areas behind it come from one measurement.

    ``pipeline.summarise`` adds these areas up across a collection, and the
    front page prints the division. If the pair and the quotient could ever be
    computed differently, the collection figure and the per-page figures beside
    it would drift apart, which is precisely the bug this pair exists to close.
    """
    words = [Box(0.1, 0.1 + 0.05 * i, 0.6, 0.02) for i in range(10)]
    boxes = [Redaction(box=words[i], kind=RedactionKind.VECTOR) for i in range(3)]
    redacted, inked = content_area(boxes, words[3:], (612, 792))
    assert inked > 0
    assert redacted / inked == pytest.approx(redaction_ratio(boxes, words[3:], (612, 792)))


def test_content_area_is_in_square_points_so_pages_of_different_sizes_add_up():
    """A cell of the grid is not a fixed area, and pages are not one size.

    The grid is always 800 cells across, so a cell on a legal page covers more
    of the world than a cell on a postcard. Adding raw cell counts across a
    mixed collection would quietly weigh the small pages more heavily, so the
    areas come back in square points.
    """
    whole_page = [Redaction(box=Box(0, 0, 1, 1), kind=RedactionKind.VECTOR)]
    for width, height in ((612.0, 792.0), (612.0, 1008.0), (595.0, 842.0)):
        redacted, inked = content_area(whole_page, [], (width, height))
        assert redacted == pytest.approx(width * height, rel=0.001)
        assert inked == pytest.approx(width * height, rel=0.001)

    letter, _ = content_area(whole_page, [], (612.0, 792.0))
    legal, _ = content_area(whole_page, [], (612.0, 1008.0))
    assert legal > letter, "a bigger sheet blacked out is more content withheld"


def test_a_page_with_nothing_on_it_has_no_content_to_measure():
    """Zero, and not a division by it. The caller decides what that means."""
    assert content_area([], [], (612, 792)) == (0.0, 0.0)


def test_ratio_grows_monotonically_as_more_is_withheld():
    """Half the lines withheld reads about half, and it only goes up."""
    words = [Box(0.1, 0.1 + 0.04 * i, 0.6, 0.02) for i in range(10)]
    previous = -1.0
    for count in range(11):
        boxes = [Redaction(box=words[i], kind=RedactionKind.VECTOR) for i in range(count)]
        surviving = words[count:]
        ratio = redaction_ratio(boxes, surviving, (612, 792))
        assert ratio >= previous
        previous = ratio
    assert previous == pytest.approx(1.0, abs=0.001)


def test_a_scan_with_one_box_is_not_a_fully_withheld_page():
    """No text layer is not the same as no content.

    On a scan there are no word boxes to measure against, and measuring
    against the boxes alone would report every scanned page that has a
    redaction on it as 100% withheld - which would put a wall of red across the
    ledger for a production that is mostly readable. The ink in the rendering
    is the content region.
    """
    image = synth.typed_page(redactions=SCAN_BOXES)
    result = analyse_page(RawPage(chars=[], rects=[]), image)

    assert len(result.redactions) == 3
    assert 0.3 < result.ratio < 0.8, result.ratio
    assert result.ink_box is not None
    assert result.ink_box.w > 0.7 and result.ink_box.h > 0.7
    # Boxes must be plain floats: numpy scalars pass every test here and then
    # fail in json.dumps at the end of the build.
    assert all(type(v) is float for v in (result.ink_box.x, result.ink_box.w))
    assert isinstance(result.ratio, float) and type(result.ratio) is float


def test_analyse_page_reports_the_ratio_and_the_inked_region(tmp_path):
    """End to end on a real PDF: boxes, ratio, ink box, and one leak."""
    path = memo(tmp_path, [synth.RedactionSpec(90, CLEAR_Y, 200, 14, hidden_text="Gregory Aldana")])
    page = raw_page(path)
    result = analyse_page(page, crop_renderer=pdf_renderer(path))

    assert isinstance(result, RedactionFindings)
    assert [f.text for f in result.hidden] == ["Gregory Aldana"]
    assert len(result.redactions) == 1
    assert result.redactions[0].kind is RedactionKind.VECTOR
    assert 0.0 < result.ratio < 0.2  # one short box on a page of text
    assert result.ink_box is not None
    assert result.ink_box.w > 0.5 and result.ink_box.h > 0.5


def test_analyse_page_merges_vector_and_raster_and_warns_about_dark_bands():
    """A block in the pixels with no rectangle behind it is called out.

    A uniform dark band across a scan is genuinely indistinguishable from a
    redaction - it is flat, black, solid and rectangular because it is. It gets
    counted, and the warning says so rather than pretending otherwise.
    """
    page = RawPage(rects=[Rect(x0=90, top=600, x1=290, bottom=616, seq=100)], chars=[])
    image = synth.blank_page()
    draw = ImageDraw.Draw(image)
    draw.rectangle([187, 1250, 604, 1283], fill=0)  # the same box, in pixels
    draw.rectangle([100, 200, 1100, 260], fill=0)  # a dark band, not in the PDF

    result = analyse_page(page, image)
    kinds = [r.kind for r in result.redactions]
    assert kinds.count(RedactionKind.VECTOR) == 1, "the vector box must not be duplicated"
    assert kinds.count(RedactionKind.RASTER) == 1
    assert any("dark scan band" in w for w in result.warnings)


def test_analyse_page_derives_the_resolution_from_the_image():
    """A 300 dpi render must not turn a hairline rule into a redaction.

    The pixel thresholds are calibrated at 150 dpi. A page rendered at 300 has
    twice the pixels for the same ink, so a 3.6pt rule stands 15px tall - over
    the floor if you assume the resolution, comfortably under it once you work
    the resolution out from the image against the page size.
    """
    image = synth.blank_page(2550, 3300)  # letter at 300 dpi
    ImageDraw.Draw(image).rectangle([300, 1000, 1100, 1014], fill=0)  # 801 x 15 px

    assert analyse_page(RawPage(), image).redactions == []
    # The same pixels, told they are 150 dpi, are a redaction-shaped block.
    assert len(find_visible_redactions(image, dpi=150)) == 1


# ==========================================================================
# 8. The shared imaging primitives
# ==========================================================================


def test_connected_components_matches_a_flood_fill():
    """The labeller is hand-written numpy; check it against the obvious version."""
    rng = np.random.default_rng(7)
    for _ in range(40):
        mask = rng.random((rng.integers(1, 20), rng.integers(1, 20))) < rng.uniform(0.1, 0.7)
        for connectivity in (4, 8):
            labels, components = connected_components(mask, connectivity=connectivity)
            assert _flood_fill_count(mask, connectivity) == len(components)
            for comp in components:
                selected = labels == comp.label
                rows, cols = np.nonzero(selected)
                assert (comp.x, comp.y) == (cols.min(), rows.min())
                assert comp.w == cols.max() - cols.min() + 1
                assert comp.h == rows.max() - rows.min() + 1
                assert comp.area == int(selected.sum())
            assert bool((labels > 0).any()) == bool(mask.any())
            assert not (labels > 0)[~mask].any()


def _flood_fill_count(mask: np.ndarray, connectivity: int) -> int:
    offsets = (
        [(-1, 0), (1, 0), (0, -1), (0, 1)]
        if connectivity == 4
        else [(dy, dx) for dy in (-1, 0, 1) for dx in (-1, 0, 1) if (dy, dx) != (0, 0)]
    )
    height, width = mask.shape
    seen = np.zeros_like(mask)
    total = 0
    for y in range(height):
        for x in range(width):
            if mask[y, x] and not seen[y, x]:
                total += 1
                stack = [(y, x)]
                seen[y, x] = True
                while stack:
                    cy, cx = stack.pop()
                    for dy, dx in offsets:
                        ny, nx = cy + dy, cx + dx
                        if 0 <= ny < height and 0 <= nx < width and mask[ny, nx] and not seen[ny, nx]:
                            seen[ny, nx] = True
                            stack.append((ny, nx))
    return total


def test_connected_components_labels_a_full_page_in_time():
    """A page has to be labelled in well under the frame the pipeline allows.

    Budget 150 ms for 1275x1650 at 150 dpi. Measured on this container: 24 ms
    for a typed page with 1,486 components. The assertion is loose enough not
    to flake on a loaded machine and tight enough to catch an accidental
    per-pixel Python loop, which would be about a hundred times over.
    """
    mask = binarise(to_gray(scanned_page_with_decoys()))
    assert mask.shape == (1650, 1275)
    connected_components(mask)  # warm up: the first big allocation is not the cost
    best = min(_time(lambda: connected_components(mask)) for _ in range(5))
    assert best < 0.150, f"{best * 1000:.0f} ms"


def _time(fn) -> float:
    start = time.perf_counter()
    fn()
    return time.perf_counter() - start


def test_components_are_labelled_in_raster_order():
    """Determinism: same bytes in, same order out (guarantee 6)."""
    mask = np.zeros((20, 20), dtype=bool)
    mask[15:18, 2:5] = True
    mask[2:5, 12:15] = True
    mask[2:5, 2:5] = True
    _, components = connected_components(mask)
    assert [(c.y, c.x) for c in components] == [(2, 2), (2, 12), (15, 2)]


def test_uniformity_and_the_empty_patch():
    """An empty patch is not uniform: we have not seen anything.

    Both callers depend on this. A redaction candidate we cannot measure is
    rejected, and a hidden-text box we cannot measure falls back to the content
    stream instead of being cleared by a crop that does not exist.
    """
    flat = np.full((30, 30), 7, dtype=np.uint8)
    assert uniformity(flat) == (0.0, 0.0, 7.0)
    assert is_uniform(flat)

    noisy = np.random.default_rng(1).integers(0, 255, (30, 30)).astype(np.uint8)
    assert not is_uniform(noisy)

    std, spread, mean = uniformity(np.zeros((0, 0), dtype=np.uint8))
    assert std == float("inf") and spread == float("inf") and mean == 0.0
    assert not is_uniform(np.zeros((0, 0), dtype=np.uint8))


def test_binarise_and_otsu():
    """Ink is dark. Otsu splits paper from toner; an explicit cut means black."""
    page = to_gray(synth.typed_page())
    threshold = otsu_threshold(page)
    assert 30 < threshold < 200
    assert 0.001 < binarise(page).mean() < 0.2  # a text page is mostly paper

    # Otsu has to follow the histogram it is given, not a remembered number:
    # the same document scanned dark and scanned light needs two answers.
    rng = np.random.default_rng(2)
    def bimodal(low, high):
        picks = rng.random((200, 200)) < 0.35
        values = np.where(picks, rng.normal(low, 3, (200, 200)), rng.normal(high, 3, (200, 200)))
        return np.clip(values, 0, 255).astype(np.uint8)

    assert otsu_threshold(bimodal(10, 60)) < 40 < otsu_threshold(bimodal(200, 240))

    assert binarise(np.full((4, 4), 200, np.uint8), 60).sum() == 0
    assert binarise(np.zeros((4, 4), np.uint8), 60).all()
    # A page of one flat colour has nothing to separate, so nothing is ink.
    assert not binarise(np.full((8, 8), 128, np.uint8)).any()


def test_to_gray_accepts_what_the_pipeline_actually_has():
    """PIL pages, numpy arrays, RGB and RGBA all reduce to one grey plane."""
    rgb = Image.new("RGB", (4, 4), (255, 0, 0))
    assert to_gray(rgb).shape == (4, 4)
    assert to_gray(rgb)[0, 0] == 76  # 0.299 * 255, Rec. 601
    assert to_gray(np.zeros((4, 4), np.uint8)).dtype == np.uint8
    assert to_gray(Image.new("RGBA", (4, 4), (0, 0, 0, 0)))[0, 0] == 0  # not composited
