"""From a folder of files to a Collection: the decisions, end to end.

These tests run the real pipeline over real PDFs generated by ``tests/synth.py``
- poppler renders them, Tesseract reads the ones with no text layer - because
the properties that matter here are exactly the ones a stub would paper over:
whether the PDF's own text is trusted, whether a page that looks like garbage
gets read again from the pixels, and whether a failed redaction is caught before
anything is written.

Speed is a feature of a test suite that people run, so every document here is
one to three pages, ``workers=1`` (the pool adds a second of process startup and
hides the traceback of anything that goes wrong in it), and the render config is
one small WebP - AVIF encoding is slow and is ``ingest/raster.py``'s business,
not this module's.

The safety tests are the reason this file exists. Guarantee 4 says text a
redaction failed to remove is never published; a test that only checks the flag
would pass while the text sat in ``data/<doc>/<n>.json``, so they assert on the
built output instead.
"""

# ruff: noqa: RUF001
# Two fixtures below are prose in Cyrillic and Devanagari, because the bug
# these tests pin is a collection that is not all in one alphabet. Every
# non-Latin character in this file is deliberate.

from __future__ import annotations

from itertools import pairwise
from pathlib import Path

import pytest

import synth
from stackroom import model
from stackroom.build.site import build_site
from stackroom.config import Config
from stackroom.ingest import redaction
from stackroom.ingest.discover import SourceFile
from stackroom.model import (
    Box,
    Collection,
    CollectionStats,
    Document,
    OcrQuality,
    Page,
    PageVerdict,
    Redaction,
    RedactionKind,
    TextSource,
    Word,
)
from stackroom.pipeline import (
    PageJob,
    SafetyStop,
    _split_cjk,
    _title_for,
    _width_over_height,
    annotate_document,
    build_collection,
    check_safety,
    process_page,
    summarise,
)

CLEAR_Y = 200.0
"""A band of the page, in PDF user space, that ``synth.born_digital_pdf`` leaves
empty: its body text stops around y=247. A box put here covers nothing but what
the fixture deliberately hides under it, so a recovered leak is exactly the
planted string and not the planted string interleaved with the prose."""


def fast_config(**overrides) -> Config:
    """The default configuration, made cheap enough to run in a test.

    Only rendering is changed. The OCR mode, the language codes and the safety
    policy are the shipped defaults on purpose: they are what is under test.
    """
    cfg = Config()
    cfg.render.dpi = 100
    cfg.render.widths = [600]
    cfg.render.thumb_width = 120
    cfg.render.formats = ["webp"]
    cfg.search.enabled = False
    for key, value in overrides.items():
        setattr(cfg, key, value)
    return cfg


def collection_in(root: Path, cfg: Config | None = None):
    return build_collection(root, cfg or fast_config(), root.parent / "out", workers=1)


# ==========================================================================
# 1. where a page's text comes from
# ==========================================================================


@pytest.fixture(scope="module")
def born_digital(tmp_path_factory):
    """A two-page PDF with a real text layer, built and read once."""
    root = tmp_path_factory.mktemp("born-digital") / "papers"
    root.mkdir()
    synth.born_digital_pdf(root / "memo.pdf", pages=2)
    return collection_in(root)


def test_a_pdf_with_its_own_text_layer_is_read_from_the_file_not_the_pixels(born_digital):
    """Recognising a page that already has perfect text is slow and worse.

    This is a regression test. The pipeline passes ``cfg.ocr.languages`` -
    Tesseract's codes, ``["eng"]`` - into the quality check, which measures the
    stopword ratio against ISO 639-1 lists (``"en"``). When those codes were
    passed through unmapped, no token matched any list, the ratio came back
    0.00 on flawless English prose, every page was judged garbage, and the
    whole collection was re-read by OCR: slower, worse text, and a text layer
    replaced for no reason.
    """
    collection, outcomes = born_digital
    assert len(outcomes) == 2
    for outcome in outcomes:
        page = outcome.page
        assert outcome.error is None
        assert page.source is TextSource.EMBEDDED, outcome.warnings
        assert page.quality.verdict is PageVerdict.GOOD, page.quality.reasons
        assert page.quality.stopword_ratio > 0.25, (
            "English prose scored like OCR garbage; the language codes did not "
            f"reach the stopword lists: {page.quality.reasons}"
        )
    assert collection.stats.ocr_pages == 0
    assert not [w for o in outcomes for w in o.warnings if "unusable" in w]


def test_the_words_read_from_the_file_are_the_words_on_the_page(born_digital):
    """A text layer that parses but says nothing is the failure this catches."""
    _, outcomes = born_digital
    words = [w.text for w in outcomes[0].page.words]
    assert "MEMORANDUM" in words
    assert "Commission" in words
    assert len(words) > 100
    assert outcomes[0].page.lines[0].startswith("MEMORANDUM")


def test_tesseract_language_codes_survive_the_trip_to_the_quality_check(tmp_path):
    """The same regression, on one page, with nothing else in the way.

    ``ocr_languages=("eng",)`` is what ``stackroom.toml`` tells operators to
    write and what the default config holds, so the pipeline must cope with it
    wherever it hands those codes on.
    """
    path = synth.born_digital_pdf(tmp_path / "memo.pdf", pages=1)
    outcome = process_page(
        PageJob(
            pdf=str(path),
            doc_id="memo",
            number=1,
            media_dir=str(tmp_path / "media"),
            media_prefix="media/memo",
            dpi=100,
            widths=(600,),
            thumb_width=120,
            formats=("webp",),
            ocr_languages=("eng",),
        )
    )
    assert outcome.page.source is TextSource.EMBEDDED
    assert outcome.page.quality.stopword_ratio > 0.25
    assert outcome.page.quality.verdict is PageVerdict.GOOD


RUSSIAN_PROSE = (
    "В соответствии с требованиями закона все документы были переданы в комиссию "
    "для рассмотрения и для последующего опубликования на официальном сайте "
    "ведомства. Ответ поступил через одиннадцать месяцев и состоял из четырёхсот "
    "страниц, значительная часть которых была изъята из состава дела."
)

HINDI_PROSE = (
    "आयोग ने निदेशक के कार्यालय और ठेकेदार प्राधिकरण के बीच मार्च से सितंबर तक की अवधि "
    "के सभी पत्राचार की मांग की थी। उत्तर ग्यारह महीने बाद आया और उसमें चार सौ पृष्ठ थे "
    "जिनमें से एक बड़ा हिस्सा रोक लिया गया था।"
)

_FONTS = {
    "DejaVu": "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "FreeSans": "/usr/share/fonts/truetype/freefont/FreeSans.ttf",
}


def prose_pdf(path: Path, text: str, font_name: str, pages: int = 1) -> Path:
    """A born-digital PDF of *text*, in a font that can draw it.

    ``synth.born_digital_pdf`` uses Helvetica, which has no Cyrillic and no
    Devanagari, so a non-Latin fixture needs its own generator. Everything else
    about the page is deliberately ordinary: real glyphs, a real text layer,
    nothing wrong with it.
    """
    from reportlab.lib.pagesizes import LETTER
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.pdfgen import canvas

    font_path = _FONTS[font_name]
    if not Path(font_path).is_file():  # pragma: no cover - depends on the host
        pytest.skip(f"{font_name} is not installed on this machine")
    pdfmetrics.registerFont(TTFont(font_name, font_path))
    _width, height = LETTER
    c = canvas.Canvas(str(path), pagesize=LETTER)
    words = text.split()
    for _ in range(pages):
        c.setFont(font_name, 11)
        y, line, i = height - 90, [], 0
        while y > 110:
            line.append(words[i % len(words)])
            i += 1
            if len(line) >= 9:
                c.drawString(72, y, " ".join(line))
                line = []
                y -= 16
        c.showPage()
    c.save()
    return path


def test_a_russian_page_in_a_collection_declared_english_is_left_alone(tmp_path):
    """The defect, end to end, in the configuration an operator really has.

    ``ocr.languages`` is Tesseract's list - what the recogniser should expect
    on a *scan*. It used to be handed to the quality check as the list of
    languages whose stopwords to count, so a born-digital Russian page in a
    collection declared ``["eng"]`` scored a stopword ratio of zero, was told
    "the PDF's own text layer does not read as language; re-OCR this page", and
    was either re-read by an English-only recogniser or published as
    unreadable - telling the reader that search cannot find anything on a page
    whose text is perfect.

    Declaring ``["eng", "rus"]`` is not the workaround: it measurably degrades
    the English scans in the same collection.
    """
    root = tmp_path / "papers"
    root.mkdir()
    prose_pdf(root / "russian.pdf", RUSSIAN_PROSE, "DejaVu")
    _, outcomes = collection_in(root)

    page = outcomes[0].page
    assert page.source is TextSource.EMBEDDED, outcomes[0].warnings
    assert page.quality.verdict is PageVerdict.GOOD, page.quality.reasons
    assert page.quality.stopword_ratio > 0.25
    assert page.language == "ru"
    assert not any("re-ocr" in r.lower() for r in page.quality.reasons)
    assert not any("unusable" in w for w in outcomes[0].warnings)


def test_a_page_in_an_undeclared_language_is_reported_once_to_the_operator(tmp_path):
    """Four hundred Russian pages in a collection you called English is news.

    The note is per page and identical, so the CLI groups it into one line with
    a count - which is the only form in which it is worth printing.
    """
    root = tmp_path / "papers"
    root.mkdir()
    prose_pdf(root / "russian.pdf", RUSSIAN_PROSE, "DejaVu", pages=3)
    _, outcomes = collection_in(root)

    notes = {w for o in outcomes for w in o.warnings if "reads as" in w}
    assert len(notes) == 1, notes
    note = notes.pop()
    assert "Russian" in note and "English" in note
    assert sum(1 for o in outcomes for w in o.warnings if w == note) == 3

    # And it stays quiet when there is nothing to say.
    english = tmp_path / "english"
    english.mkdir()
    synth.born_digital_pdf(english / "memo.pdf", pages=1)
    _, quiet = collection_in(english)
    assert not [w for o in quiet for w in o.warnings if "reads as" in w]


def test_a_page_in_a_script_with_no_word_list_is_not_called_garbage(tmp_path):
    """Hindi, Thai, Japanese, Korean, Hebrew: zero against every list we ship.

    A zero stopword ratio means two different things and only one of them is a
    reason to act. This page is judged on its other signals and said so, rather
    than being condemned and re-read by a recogniser that was never asked to
    read Devanagari.
    """
    root = tmp_path / "papers"
    root.mkdir()
    prose_pdf(root / "hindi.pdf", HINDI_PROSE, "FreeSans")
    _, outcomes = collection_in(root)

    page = outcomes[0].page
    assert page.source is TextSource.EMBEDDED, outcomes[0].warnings
    assert page.quality.verdict is PageVerdict.GOOD, page.quality.reasons
    assert page.quality.garbage_ratio == 0.0
    assert any("no stopword list" in r for r in page.quality.reasons)
    assert any("no stopword list" in w for w in outcomes[0].warnings)


def test_a_scan_with_no_text_layer_is_recognised_from_the_image(tmp_path):
    """The other half of the decision: no text layer means read the pixels.

    If this comes back EMBEDDED or NONE, every scanned collection - which is
    most of them - is published unsearchable.
    """
    root = tmp_path / "papers"
    root.mkdir()
    synth.image_only_pdf(root / "scan.pdf", [synth.typed_page(lines=12)])
    collection, outcomes = collection_in(root)

    page = outcomes[0].page
    assert page.source is TextSource.OCR, outcomes[0].warnings
    assert len(page.words) > 20, "nothing was recognised on a clean typed page"
    assert collection.stats.ocr_pages == 1
    assert any(word.conf >= 0 for word in page.words), "OCR words carry a confidence"


def test_a_page_carries_the_size_of_the_page_it_came_from(born_digital):
    """Letter paper, in points. The page template lays the scan out from this."""
    _, outcomes = born_digital
    assert outcomes[0].page.width_pt == pytest.approx(612, abs=1)
    assert outcomes[0].page.height_pt == pytest.approx(792, abs=1)


def test_the_rendered_images_are_written_and_recorded(born_digital):
    """The page cannot be read next to its scan if the scan was never encoded."""
    _, outcomes = born_digital
    page = outcomes[0].page
    assert [v.format for v in page.images] == ["webp"]
    assert page.images[0].width == 600
    assert page.images[0].path.startswith("media/memo/")
    assert page.thumbs and page.thumbs[0].width == 120


# ==========================================================================
# 2. failed redactions
# ==========================================================================


@pytest.fixture(scope="module")
def failed_redaction(tmp_path_factory):
    """A one-page release with a name painted under a black box."""
    root = tmp_path_factory.mktemp("leak") / "papers"
    root.mkdir()
    synth.born_digital_pdf(
        root / "release.pdf",
        pages=1,
        redactions={
            1: [
                synth.RedactionSpec(
                    90, CLEAR_Y, 200, 14, hidden_text="Gregory Aldana", code="(b)(6)"
                )
            ]
        },
    )
    return collection_in(root)


def test_a_failed_redaction_is_found_and_carried_back_to_the_operator(failed_redaction):
    """Finding it is the point; showing what leaked is how it gets judged."""
    _, outcomes = failed_redaction
    assert [h.text for h in outcomes[0].hidden] == ["Gregory Aldana"]
    assert outcomes[0].hidden[0].redacted_repr() == "####### ######"
    assert outcomes[0].page.redactions, "the box itself is still on the ledger"


def test_the_default_policy_stops_the_build_on_a_failed_redaction(failed_redaction):
    """The strict setting is the default because the operator is usually the
    last person who could have caught it."""
    _, outcomes = failed_redaction
    with pytest.raises(SafetyStop) as caught:
        check_safety(outcomes, fast_config())
    message = str(caught.value)
    assert "1 page(s)" in message
    assert "readable in the file" in message
    assert "Gregory" not in message, "the leaked text must not travel in an exception message"
    assert [f[0] for f in caught.value.findings] == ["release"]
    assert caught.value.findings[0][1] == 1


def test_hidden_text_never_reaches_the_page_object(failed_redaction):
    """Guarantee 4, at the seam where the site builder would read it.

    Even in ``warn`` mode this text is dropped: what the operator publishes is
    the document, not our transcription of what somebody tried to remove.
    """
    _, outcomes = failed_redaction
    page = outcomes[0].page
    assert page.words, "dropping the covered words must not empty the page"
    for token in ("Gregory", "Aldana"):
        assert not [w for w in page.words if token in w.text]
        assert not [line for line in page.lines if token in line]
    assert "Aldana" not in page.token_text


def test_hidden_text_never_reaches_the_built_site(tmp_path, failed_redaction):
    """The assertion that would have caught it in ``data/<doc>/<n>.json``.

    The published original is the exception, and deliberately so: guarantee 2
    says the file is downloadable byte for byte, and a released PDF with a
    failed redaction in it is evidence of the failure. Everything Stackroom
    *generates* has to be clean.
    """
    collection, outcomes = failed_redaction
    cfg = fast_config()
    cfg.safety.hidden_text = "warn"
    out = tmp_path / "site"
    build_site(collection, cfg, out)

    generated = [
        path
        for path in out.rglob("*")
        if path.is_file() and "files" not in path.relative_to(out).parts
    ]
    assert generated
    for path in generated:
        text = path.read_bytes().decode("utf-8", errors="ignore")
        for token in ("Gregory", "Aldana"):
            assert token not in text, f"leaked into {path.relative_to(out)}"

    original = out / "files" / "release.pdf"
    assert original.is_file(), "the original must still be published"
    assert outcomes[0].hidden, "the fixture is only meaningful if a leak was planted"


def test_warn_reports_the_findings_and_lets_the_build_continue(failed_redaction):
    """The operator who has read the finding and decided may publish anyway.

    ``ignore`` is not offered - the choice is between stopping and being told -
    so ``warn`` has to return the findings rather than swallow them.
    """
    _, outcomes = failed_redaction
    cfg = fast_config()
    cfg.safety.hidden_text = "warn"
    findings, unchecked = check_safety(outcomes, cfg)
    assert [f[0] for f in findings] == ["release"]
    assert [h.text for h in findings[0][2]] == ["Gregory Aldana"]
    assert unchecked == []


def test_a_clean_release_passes_the_safety_gate(born_digital):
    """The gate has to be quiet when there is nothing to say, or it is noise."""
    _, outcomes = born_digital
    assert check_safety(outcomes, fast_config()) == ([], [])


def test_a_redaction_check_that_crashed_stops_the_build_as_well(tmp_path, monkeypatch):
    """"We could not look" is not "we looked and it was clean".

    This is the quieter of the two failures and the more dangerous one, because
    an operator reads a build with no findings as a build with nothing to find.
    """
    root = tmp_path / "papers"
    root.mkdir()
    synth.born_digital_pdf(root / "memo.pdf", pages=1)

    def explode(*args, **kwargs):
        raise RuntimeError("the crop renderer died")

    monkeypatch.setattr(redaction, "analyse_page", explode)
    _, outcomes = collection_in(root)

    assert outcomes[0].analysis_failed is True
    assert not outcomes[0].hidden
    assert any("do not know whether anything is hidden" in w for w in outcomes[0].warnings)

    with pytest.raises(SafetyStop) as caught:
        check_safety(outcomes, fast_config())
    assert "could not be checked" in str(caught.value)


def test_an_unchecked_page_is_reported_under_warn_rather_than_hidden(tmp_path, monkeypatch):
    root = tmp_path / "papers"
    root.mkdir()
    synth.born_digital_pdf(root / "memo.pdf", pages=1)
    monkeypatch.setattr(
        redaction, "analyse_page", lambda *a, **k: (_ for _ in ()).throw(RuntimeError("no"))
    )
    _, outcomes = collection_in(root)
    cfg = fast_config()
    cfg.safety.hidden_text = "warn"
    findings, unchecked = check_safety(outcomes, cfg)
    assert findings == []
    assert unchecked == [("memo", 1)]


def test_one_damaged_file_does_not_stop_a_collection(tmp_path):
    """A corrupt file in a 3,000-page production is a note, not a build failure.

    The rest of the module is built around this: ``process_page`` never raises,
    and ``_jobs_for`` is wrapped in a handler that emits "skipped: ..." for
    exactly this case. A collection that refuses to build over one bad file out
    of 3,000 is a collection nobody publishes.

    This was an ``xfail`` for as long as ``build_collection`` called
    ``pdf.document_meta()`` one line *above* the ``try`` that guarded
    ``_jobs_for()``: a file with a ``%PDF`` header and damaged contents raised
    ``PdfDamagedError`` out of the whole build instead of being skipped. Both
    calls are inside the handler now, which is what this asserts. The shape of
    the regression is one line moving back out of that ``try``, so the file
    below is written to be exactly what ``document_meta`` chokes on rather than
    what the renderer does.
    """
    root = tmp_path / "papers"
    root.mkdir()
    (root / "broken.pdf").write_bytes(b"%PDF-1.4\nthis is not a PDF at all\n%%EOF\n")
    synth.born_digital_pdf(root / "good.pdf", pages=1)

    notes: list[str] = []
    collection, outcomes = build_collection(
        root,
        fast_config(),
        tmp_path / "out",
        workers=1,
        progress=lambda event: notes.append(f"{event.label}: {event.detail}"),
    )
    assert [doc.id for doc in collection.documents] == ["good"]
    assert len(outcomes) == 1
    assert any("broken" in note and "skipped" in note for note in notes)


def test_the_page_count_is_offered_before_a_single_page_is_rendered(tmp_path):
    """The size of a collection is knowable at discovery, and is refused there.

    ``cli._page_ceiling`` used to run after the ingest, so a 60,000-page
    production was read in full - hours of pdftoppm and Tesseract - and then
    refused. Discovery already asks both parsers how many pages each file has,
    so the count is free at that point; what this pins is that raising from
    ``on_counted`` stops the build with nothing rasterised.
    """
    root = tmp_path / "papers"
    root.mkdir()
    synth.born_digital_pdf(root / "memo.pdf", pages=3)
    out = tmp_path / "out"

    seen: list[int] = []

    class TooBig(RuntimeError):
        pass

    def refuse(pages: int) -> None:
        seen.append(pages)
        raise TooBig(f"{pages} pages is too many")

    with pytest.raises(TooBig):
        build_collection(root, fast_config(), out, workers=1, on_counted=refuse)

    assert seen == [3], "counted once, with the whole queue"
    rendered = list((out / "media").rglob("*")) if (out / "media").exists() else []
    assert [p for p in rendered if p.is_file()] == [], "nothing was rendered before the refusal"


def test_the_page_count_offered_is_the_number_of_pages_read(tmp_path):
    """Whatever the ceiling is checked against has to be what gets built."""
    root = tmp_path / "papers"
    root.mkdir()
    synth.born_digital_pdf(root / "one.pdf", pages=2)
    synth.born_digital_pdf(root / "two.pdf", pages=1)

    counted: list[int] = []
    collection, outcomes = build_collection(
        root, fast_config(), tmp_path / "out", workers=1, on_counted=counted.append
    )
    assert counted == [3]
    assert collection.stats.pages == 3 == len(outcomes)


def test_source_date_epoch_pins_the_one_thing_that_is_not_the_input(tmp_path, monkeypatch):
    """Guarantee 6 needs a build stamp that is a function of something.

    ``built_at`` is written into ``manifest.json`` and printed into the footer of
    every page, so without this two people who build the same folder on
    different days differ in every file and "same input bytes, same output
    bytes" is false as stated. ``SOURCE_DATE_EPOCH`` is the
    reproducible-builds convention for exactly this.
    """
    root = tmp_path / "papers"
    root.mkdir()
    synth.born_digital_pdf(root / "memo.pdf", pages=1)

    monkeypatch.setenv("SOURCE_DATE_EPOCH", "1717200000")
    first, _ = build_collection(root, fast_config(), tmp_path / "a", workers=1)
    second, _ = build_collection(root, fast_config(), tmp_path / "b", workers=1)
    assert first.build.built_at == second.build.built_at == "2024-06-01T00:00:00+00:00"

    # And the default is still the clock.
    monkeypatch.delenv("SOURCE_DATE_EPOCH")
    third, _ = build_collection(root, fast_config(), tmp_path / "c", workers=1)
    assert third.build.built_at != first.build.built_at


@pytest.mark.parametrize("value", ["", "  ", "not-a-number", "1717200000.5", "99999999999999999999"])
def test_an_unusable_source_date_epoch_is_not_silently_believed(value, monkeypatch):
    """A malformed value must not become a date, and the CLI refuses it.

    Falling back to the clock is the right thing for the library - a stray
    environment variable cannot be allowed to stop a build - but somebody who
    exported this asked for a stamp that does not move, so being quietly given
    the clock instead is the opposite of what they asked for. The CLI checks it
    up front and says so.
    """
    from stackroom import cli as cli_mod

    monkeypatch.setenv("SOURCE_DATE_EPOCH", value)
    assert model.source_date_epoch() is None
    assert model.build_timestamp()  # the clock, not a crash

    if value.strip():
        with pytest.raises(Exception) as refused:
            cli_mod._check_source_date_epoch()
        assert refused.type.__name__ == "Exit"
    else:
        cli_mod._check_source_date_epoch()  # unset is not an error


# ==========================================================================
# 3. what counts as a document
# ==========================================================================


def test_the_operators_own_files_are_not_published_as_documents(tmp_path):
    """``about.md`` and ``stackroom.toml`` live beside a collection, not in it.

    Publishing the operator's working notes as page one of the archive would be
    a memorable way to fail.
    """
    root = tmp_path / "papers"
    root.mkdir()
    (root / "about.md").write_text("# About\n\nReleased under a request in 2019.\n")
    (root / "stackroom.toml").write_text('title = "Papers"\n')
    (root / "README.md").write_text("build notes to self\n")
    (root / "notes.md").write_text("call the press officer back\n")
    synth.born_digital_pdf(root / "memo.pdf", pages=1)

    collection, outcomes = collection_in(root)
    assert [doc.id for doc in collection.documents] == ["memo"]
    assert {o.doc_id for o in outcomes} == {"memo"}
    assert collection.stats.documents == 1
    assert not [
        w for o in outcomes for w in o.page.words if "press officer" in w.text
    ]


def test_a_gap_in_the_control_numbers_is_found_end_to_end(tmp_path):
    """A gap is a page withheld in full - usually the most interesting page.

    The stamps have to be read off the rendered margins, verified across pages
    and turned into a range, all of it inside one build.
    """
    root = tmp_path / "papers"
    root.mkdir()
    synth.born_digital_pdf(
        root / "production.pdf", pages=3, bates_prefix="ABC-", bates_start=1, bates_skip={2}
    )
    collection, _ = collection_in(root)
    doc = collection.documents[0]

    assert doc.bates_prefix == "ABC-"
    assert doc.bates_gaps == [("ABC-000002", "ABC-000002")]
    assert [page.bates for page in doc.pages] == ["ABC-000001", "ABC-000003", "ABC-000004"]


def test_an_unbroken_production_reports_no_gaps(tmp_path):
    """A false gap is an accusation, so the quiet case has to stay quiet."""
    root = tmp_path / "papers"
    root.mkdir()
    synth.born_digital_pdf(root / "production.pdf", pages=3, bates_prefix="ABC-")
    collection, _ = collection_in(root)
    assert collection.documents[0].bates_gaps == []


def test_an_exemption_code_printed_beside_a_box_ends_up_on_the_page(failed_redaction):
    """The code is why the box is there, and it is scanned out of the text."""
    collection, _ = failed_redaction
    assert collection.documents[0].pages[0].exemptions == ["b(6)"]


@pytest.fixture(scope="module")
def withheld_in_full(tmp_path_factory):
    """A two-page release whose second page is withheld end to end.

    The stamp is reversed out of the black rectangle in white, which is how an
    agency prints one, so every character the box covers is a character painted
    on top of it and nothing at all is hidden underneath.
    """
    root = tmp_path_factory.mktemp("withheld") / "papers"
    root.mkdir()
    synth.withheld_in_full_pdf(root / "release.pdf", code="(b)(5)")
    return collection_in(root)


def test_a_page_withheld_in_full_keeps_its_transcription(withheld_in_full):
    """End to end: the sheet an agency withheld whole is still readable as one.

    ``redaction._scan_hidden`` recorded "this box obliterated text" from a list
    whose only members were the *spaces* between the heading's plainly visible
    words - the one part of that rectangle whose own cells are solid box colour
    - before it tested whether any of it was whitespace. The box therefore went
    into ``findings.covered``, ``_drop_hidden`` withheld every token it touched,
    and the page came out of the pipeline with no words on it at all: the
    reader is shown a blank transcription of a page whose whole content is the
    sentence saying it was withheld.

    Nothing was ever reported as leaking, which is what made it quiet.
    """
    _, outcomes = withheld_in_full
    page = outcomes[1].page
    assert outcomes[1].hidden == [], "nothing is hidden under this box and nothing may be reported"
    assert page.words, "the page withheld in full lost its whole transcription"
    assert page.lines[0] == "(b)(5) PAGE WITHHELD IN FULL"
    assert page.redactions, "the box is still a redaction: it is black and opaque"
    assert page.redaction_ratio == pytest.approx(1.0)


def test_a_page_withheld_in_full_keeps_the_code_stamped_on_it(withheld_in_full):
    """And the ledger keeps the exemption, which is the whole point of the page.

    A code printed *inside* the box is one of the two ordinary layouts, and it
    is the one that went missing: withhold the transcription and the code goes
    with it, so a release with six pages withheld under (b)(5) reported five.
    """
    collection, _ = withheld_in_full
    doc = collection.documents[0]
    assert doc.pages[1].exemptions == ["b(5)"]
    assert [p.number for p in doc.pages if "b(5)" in p.exemptions] == [2]


# --------------------------------------------------------------------------
# the near field is measured in the units it says it is
#
# `exemptions.associate` scales horizontal gaps by width/height and `Page.aspect`
# is height/width, so handing one straight to the other squares the page up the
# wrong way and shrinks the near field horizontally by 1.67x - 24pt where the
# docstring promises 40. It only ever drops a code, never invents one, which is
# why it survived so long. The geometry below is the gap it lost.
# --------------------------------------------------------------------------

LETTER_W, LETTER_H = 612.0, 792.0


def _letter_page(*, code_at: float) -> tuple[Page, Redaction]:
    """A Letter page with one box and one code *code_at* points to its right.

    The code sits on the line *below* the box - 8pt of clear vertical space -
    so `_shares_a_line` says no and the near field is the only thing left to
    decide it. Everything is well clear of the header and footer bands.
    """
    box = Box(100 / LETTER_W, 300 / LETTER_H, 100 / LETTER_W, 12 / LETTER_H)
    redaction_ = Redaction(box=box, kind=model.RedactionKind.VECTOR)
    stamp = Word(
        text="(b)(6)",
        box=Box((200 + code_at) / LETTER_W, 320 / LETTER_H, 50 / LETTER_W, 12 / LETTER_H),
        line=1,
    )
    page = Page(
        number=1,
        width_pt=LETTER_W,
        height_pt=LETTER_H,
        words=[stamp],
        redactions=[redaction_],
    )
    return page, redaction_


def _annotated_page(page: Page) -> None:
    annotate_document(
        Document(id="d", title="d", filename="d.pdf", sha256="0" * 64, size_bytes=1, pages=[page])
    )


def test_the_page_hands_the_association_rule_width_over_height():
    """0.773 on Letter, not 1.294. The two are a factor of 1.67 apart."""
    page = Page(number=1, width_pt=LETTER_W, height_pt=LETTER_H)
    assert page.aspect == pytest.approx(1.294, abs=0.001)
    assert _width_over_height(page) == pytest.approx(0.7727, abs=0.0001)
    assert _width_over_height(Page(number=1, width_pt=595.0, height_pt=842.0)) == pytest.approx(
        0.7067, abs=0.0001
    )


def test_a_page_with_no_height_falls_back_instead_of_dividing_by_zero():
    """`Page.aspect` makes the same fallback for a page with no width."""
    assert _width_over_height(Page(number=1, height_pt=0.0)) == pytest.approx(0.7727, abs=0.0001)


def test_a_code_30pt_across_the_page_is_inside_the_near_field():
    """Documented as 40pt on Letter. Under the inverted ratio it was 24."""
    page, redaction_ = _letter_page(code_at=30.0)
    _annotated_page(page)
    assert redaction_.codes == ["b(6)"]


def test_a_code_60pt_across_the_page_is_still_outside_it():
    """The fix widens the near field to what it claims, not past it."""
    page, redaction_ = _letter_page(code_at=60.0)
    _annotated_page(page)
    assert redaction_.codes == []
    assert page.exemptions == ["b(6)"]  # page-level, and still counted


# ==========================================================================
# 4. splitting CJK
# ==========================================================================


def latin_word(text: str) -> Word:
    return Word(text=text, box=Box(0.1, 0.2, 0.3, 0.02), conf=88, line=3)


def test_a_cjk_word_becomes_one_word_per_character():
    """Pagefind re-segments CJK itself and counts one token per character.

    If a word here spans three characters and the index counts three, every
    highlight after it on the page lands on the wrong glyph.
    """
    split = _split_cjk([Word(text="機密文書", box=Box(0.2, 0.4, 0.4, 0.03), conf=71, line=2)])
    assert [w.text for w in split] == ["機", "密", "文", "書"]
    assert all(w.line == 2 and w.conf == 71 for w in split)


def test_the_boxes_of_a_split_word_tile_the_box_it_came_from():
    """Square, evenly spaced glyphs: proportional division is very nearly exact."""
    original = Word(text="機密文書", box=Box(0.2, 0.4, 0.4, 0.03), line=0)
    split = _split_cjk([original])
    assert sum(w.box.w for w in split) == pytest.approx(original.box.w)
    assert split[0].box.x == pytest.approx(0.2)
    assert split[-1].box.x2 == pytest.approx(original.box.x2)
    for left, right in pairwise(split):
        assert left.box.x2 == pytest.approx(right.box.x)
        assert left.box.y == original.box.y and left.box.h == original.box.h


@pytest.mark.parametrize("text", ["hello", "authority,", "(b)(6)", "12345", "COMMISSION"])
def test_a_latin_word_is_left_exactly_as_it_was(text):
    """The split must not touch the scripts it is not for.

    A Latin word broken into letters would multiply the token count by six and
    desynchronise the index on every English page in the archive.
    """
    word = latin_word(text)
    split = _split_cjk([word])
    assert len(split) == 1
    assert split[0] is word, "an untouched word should not even be copied"


@pytest.mark.parametrize("text", ["中", "あ", "한"])
def test_a_single_character_is_already_one_token(text):
    assert [w.text for w in _split_cjk([Word(text=text, box=Box(0, 0, 0.02, 0.02))])] == [text]


def test_kana_and_hangul_are_split_like_han():
    """All three are indexed per character, and all three fold to one rule."""
    assert len(_split_cjk([Word(text="ひらがな", box=Box(0, 0, 0.1, 0.02))])) == 4
    assert len(_split_cjk([Word(text="한국어", box=Box(0, 0, 0.1, 0.02))])) == 3


def test_a_mixed_page_keeps_its_order_across_the_split():
    """Order is the invariant everything downstream depends on."""
    words = [
        latin_word("Re:"),
        Word(text="機密", box=Box(0.3, 0.2, 0.2, 0.02)),
        latin_word("2019"),
    ]
    assert [w.text for w in _split_cjk(words)] == ["Re:", "機", "密", "2019"]


def test_splitting_nothing_returns_nothing():
    assert _split_cjk([]) == []


# ==========================================================================
# 5. titles
# ==========================================================================


def source_named(stem: str, slug: str = "annual-report-2019") -> SourceFile:
    return SourceFile(path=Path(f"/papers/{stem}.pdf"), sha256="", size=0, slug=slug, kind="pdf")


@pytest.mark.parametrize(
    ("claimed", "expected"),
    [
        (None, "annual report 2019"),
        ("", "annual report 2019"),
        ("   ", "annual report 2019"),
        ("untitled", "annual report 2019"),
        ("Untitled Document", "annual report 2019"),
        ("Document1", "annual report 2019"),
        ("scan", "annual report 2019"),
        ("Microsoft Word - final(2).doc", "annual report 2019"),
        ("annual_report-2019.pdf", "annual report 2019"),
        ("3f2504e0-4f89-11d3-9a0c-0305e82c3301", "annual report 2019"),
        ("ab", "annual report 2019"),
        ("Report of the Commission of Inquiry", "Report of the Commission of Inquiry"),
        ("Annex B - correspondence - March - April", "Annex B - correspondence - March - April"),
    ],
)
def test_the_embedded_title_has_to_earn_its_place(claimed, expected):
    """A PDF's ``/Title`` is very often the scanner's file name or a UUID.

    The name a person chose is a better title than any of those, and this is
    the string that ends up in the page title, the browse list and the citation.
    """
    meta = {} if claimed is None else {"title": claimed}
    assert _title_for(source_named("annual_report-2019"), meta) == expected


def test_a_document_with_no_usable_name_at_all_falls_back_to_its_slug():
    """Every document needs something to be called in a list of documents."""
    assert _title_for(source_named("--", slug="doc-4"), {"title": "untitled"}) == "doc-4"


def test_a_real_title_in_the_file_is_used(born_digital):
    """``synth`` sets ``/Title``; a build must prefer it over "memo"."""
    collection, _ = born_digital
    assert collection.documents[0].title == "Synthetic release"


# ==========================================================================
# 6. summarise
# ==========================================================================


def counted_page(number: int, **kwargs) -> Page:
    """A page on a square 800pt sheet, where one grid cell is exactly 1 pt².

    `redaction.content_area` measures on a grid RATIO_GRID (800) cells wide and
    as many tall as the aspect ratio asks for, so a square 800pt page gives an
    800x800 grid and an area in square points that is just the number of cells.
    That is what makes the arithmetic below checkable with a pencil.
    """
    kwargs.setdefault("width_pt", 800.0)
    kwargs.setdefault("height_pt", 800.0)
    return Page(number=number, **kwargs)


def filling(x: float, y: float, w: float, h: float, count: int = 3) -> list[Word]:
    """*count* words whose boxes together fill exactly the given rectangle."""
    step = w / count
    return [
        Word(text="w", box=Box(x + i * step, y, step, h)) for i in range(count)
    ]


def test_the_collection_summary_counts_what_it_says_it_counts():
    """Every number on the front page and in the manifest comes from here.

    Hand-computed against a collection small enough to check by eye, because a
    statistic that is wrong is worse than one that is missing: it is quoted.

    Four pages, on square 800pt sheets so that one grid cell is one square
    point:

    ======  ===============================  ==========  =====  =========
    page    content                          area (pt²)  share  withheld
    ======  ===============================  ==========  =====  =========
    a1      text over the top half, a strip       320000   0.10      32000
            of it blacked out
    a2      blacked out end to end: one box       640000   1.00     640000
            over the whole sheet, no words
            left at all
    a3      blank: no text, no boxes                   0      -          -
    b1      text over the top half, nothing       320000   0.00          0
            withheld
    ======  ===============================  ==========  =====  =========

    So:

    * ``redaction_ratio`` = 672000 / 960000 = **0.70** - the withheld area over
      the content of the two pages that carry redactions, which is what the
      front page prints and what the sentence beside it names.
    * ``redaction_ratio_collection`` = 672000 / 1280000 = **0.525** - the same
      numerator over every page.

    Neither is the mean of the per-page shares, and that is the point. The old
    code averaged the shares of the pages that had any text, which here is
    (0.10 + 0.00) / 2 = **0.05**: page a2, blacked out from edge to edge, has no
    surviving words and so did not appear in the statistic at all.
    """
    a1 = counted_page(
        1,
        words=filling(0.0, 0.0, 1.0, 0.5),
        source=TextSource.EMBEDDED,
        redactions=[Redaction(box=Box(0, 0, 0.1, 0.5), kind=RedactionKind.VECTOR)],
        redaction_ratio=0.1,
        exemptions=["b(6)"],
        language="en",
    )
    a2 = counted_page(
        2,
        source=TextSource.NONE,
        quality=OcrQuality(verdict=PageVerdict.SUSPECT),
        redactions=[Redaction(box=Box(0, 0, 1.0, 1.0), kind=RedactionKind.VECTOR)],
        redaction_ratio=1.0,
        exemptions=["b(6)", "b(7)(C)"],
    )
    a3 = counted_page(3, source=TextSource.NONE, quality=OcrQuality(verdict=PageVerdict.BLANK))
    b1 = counted_page(
        1,
        words=filling(0.0, 0.0, 1.0, 0.5, count=2),
        source=TextSource.OCR_OVERRIDE,
        quality=OcrQuality(verdict=PageVerdict.PICTORIAL),
        language="fr",
    )

    # The shares above are the ones `ingest/redaction.py` would measure for
    # these boxes, so the fixture cannot drift away from the real thing.
    for page in (a1, a2, b1):
        assert page.redaction_ratio == pytest.approx(
            redaction.redaction_ratio(
                page.redactions, [w.box for w in page.words], (page.width_pt, page.height_pt)
            )
        )

    first = Document(
        id="a", title="A", filename="a.pdf", sha256="a" * 64, size_bytes=1000,
        pages=[a1, a2, a3],
    )
    second = Document(
        id="b", title="B", filename="b.pdf", sha256="b" * 64, size_bytes=100, pages=[b1],
    )

    stats = summarise(Collection(documents=[first, second]))

    assert stats.documents == 2
    assert stats.pages == 4
    assert stats.words == 5
    assert stats.pages_with_redactions == 2
    assert stats.redaction_boxes == 2

    assert stats.redacted_pages_area_pt == pytest.approx(960_000.0)
    assert stats.collection_area_pt == pytest.approx(1_280_000.0)
    assert stats.withheld_area_pt == pytest.approx(672_000.0)
    assert stats.redaction_ratio == pytest.approx(0.70), "withheld area over the redacted pages"
    assert stats.redaction_ratio_collection == pytest.approx(0.525), "over the whole collection"
    assert stats.unmeasured_pages == 1, "the blank page can be measured neither way"

    assert stats.unreadable_pages == 1
    assert stats.pictorial_pages == 1
    assert stats.blank_pages == 1
    assert stats.ocr_pages == 1, "OCR and OCR-override are both recognised pages"
    assert stats.exemption_counts == {"b(6)": 2, "b(7)(C)": 1}
    assert list(stats.exemption_counts) == ["b(6)", "b(7)(C)"], "commonest first"
    assert stats.languages == ["en", "fr"]
    assert stats.bytes_total == 1100


def test_a_page_blacked_out_end_to_end_is_in_the_withheld_figure():
    """The regression that made the front page's number too small.

    A page withheld in full has no surviving words, and the old summary only
    looked at pages that had some, so the most completely withheld page in a
    release was the one page it did not count. Here that page is the whole
    collection: anything but 100% is the bug.
    """
    page = counted_page(
        1,
        redactions=[Redaction(box=Box(0, 0, 1.0, 1.0), kind=RedactionKind.VECTOR)],
        redaction_ratio=1.0,
    )
    doc = Document(id="a", title="A", filename="a.pdf", sha256="a" * 64, size_bytes=1, pages=[page])

    stats = summarise(Collection(documents=[doc]))

    assert stats.redaction_ratio == pytest.approx(1.0)
    assert stats.redaction_ratio_collection == pytest.approx(1.0)
    assert stats.unmeasured_pages == 0


def test_a_dense_page_counts_for_more_than_a_one_line_page():
    """Why the figure is an area and not a mean of per-page shares.

    Two pages: a full page of text with a tenth of it withheld, and a page
    carrying one short line that is gone entirely. A mean of the shares says
    55% of this release is withheld, which is a sentence a reporter would put
    in a first paragraph and which is not true of anything. The content-weighted
    figure says 12.2%, because the second page holds a fortieth as much.
    """
    dense = counted_page(
        1,
        words=filling(0.0, 0.0, 1.0, 0.8, count=4),
        redactions=[Redaction(box=Box(0, 0, 0.1, 0.8), kind=RedactionKind.VECTOR)],
        redaction_ratio=0.1,
    )
    one_line = counted_page(
        2,
        redactions=[Redaction(box=Box(0, 0, 0.2, 0.025), kind=RedactionKind.VECTOR)],
        redaction_ratio=1.0,
    )
    doc = Document(
        id="a", title="A", filename="a.pdf", sha256="a" * 64, size_bytes=1,
        pages=[dense, one_line],
    )

    stats = summarise(Collection(documents=[doc]))

    mean_of_shares = (dense.redaction_ratio + one_line.redaction_ratio) / 2
    assert mean_of_shares == pytest.approx(0.55)
    # 512000 pt² of content on the first page, 3200 on the second.
    assert stats.redacted_pages_area_pt == pytest.approx(515_200.0)
    assert stats.withheld_area_pt == pytest.approx(51_200.0 + 3_200.0)
    assert stats.redaction_ratio == pytest.approx(54_400.0 / 515_200.0)
    assert stats.redaction_ratio < 0.13


def test_the_collection_figure_is_the_per_page_figures_weighted_by_content():
    """The number on the front page has to be reconstructible from the pages.

    Somebody who reads "35% withheld" on the front page and then sees 96%, 6%,
    5%, 3% and 3% beside individual pages on ``withheld/index.html`` will try to
    get from one to the other. They can: it is those shares weighted by each
    page's content area, and nothing else.
    """
    pages = [
        counted_page(
            n,
            words=filling(0.0, 0.0, 1.0, height),
            redactions=[Redaction(box=Box(0, 0, share, height), kind=RedactionKind.VECTOR)],
            redaction_ratio=share,
        )
        for n, (share, height) in enumerate(((0.25, 0.8), (0.5, 0.2), (0.75, 0.5)), start=1)
    ]
    doc = Document(
        id="a", title="A", filename="a.pdf", sha256="a" * 64, size_bytes=1, pages=pages
    )

    stats = summarise(Collection(documents=[doc]))

    areas = [
        redaction.content_area(
            p.redactions, [w.box for w in p.words], (p.width_pt, p.height_pt)
        )[1]
        for p in pages
    ]
    expected = sum(p.redaction_ratio * a for p, a in zip(pages, areas, strict=True)) / sum(areas)
    assert stats.redaction_ratio == pytest.approx(expected)


def test_an_empty_collection_summarises_to_zero_rather_than_dividing_by_it():
    stats = summarise(Collection())
    assert stats == CollectionStats()
    assert stats.redaction_ratio == 0.0
    assert stats.redaction_ratio_collection == 0.0


def test_the_summary_of_a_real_build_agrees_with_the_documents(born_digital):
    """The statistics and the model must not be able to disagree."""
    collection, _ = born_digital
    stats = collection.stats
    assert stats.documents == len(collection.documents) == 1
    assert stats.pages == sum(d.page_count for d in collection.documents) == 2
    assert stats.words == sum(len(p.words) for d in collection.documents for p in d.pages)
    assert stats.bytes_total == collection.documents[0].size_bytes


def test_a_build_records_what_built_it(born_digital):
    """An archive earns trust by being checkable: version, digest, duration."""
    collection, _ = born_digital
    assert collection.build.version
    assert len(collection.build.source_digest) == 64
    assert collection.build.built_at
    assert collection.build.duration_seconds >= 0
